#!/usr/bin/env python3
"""
Sau khi dịch xong file _unique.txt thành _translated.tsv (CN<TAB>VN),
script này dựng lại file Lua override để mod load.

Output: scripts/phase3_speech_<char>.lua
chứa set_str("STRINGS.CHARACTERS.XD_WUKONG.<path>", "<vn>") cho mỗi entry.

Usage:
    python3 build_speech_lua.py <full.tsv> <translated_unique.tsv> <CHAR_KEY> <out.lua>

Trong đó:
    full.tsv               — output của extract_speech.py (tất cả entries)
    translated_unique.tsv  — file dịch (CN<TAB>VN, một dòng mỗi unique)
    CHAR_KEY               — vd "XD_WUKONG"
    out.lua                — file output Lua
"""
import sys
import os


def lua_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")


def main():
    if len(sys.argv) < 5:
        print(__doc__)
        sys.exit(1)
    full_tsv, vn_tsv, char_key, out_lua = sys.argv[1:5]

    # Load translation map
    vn_map = {}
    with open(vn_tsv, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) < 2:
                continue
            cn, vn = parts[0], parts[1]
            # File dịch giữ \n dưới dạng 2 ký tự; phần nạp full.tsv bên dưới lại
            # đổi chúng thành xuống dòng thật. Chuẩn hoá cả hai vế để khớp được,
            # và để lua_escape() không escape nhầm thành \\n.
            unesc = lambda s: s.replace("\\n", "\n").replace("\\t", "\t")
            vn_map[cn] = unesc(vn)
            vn_map[unesc(cn)] = unesc(vn)
    print(f"Loaded {len(vn_map)} translations")

    # Load full entries (path → cn)
    entries = []
    with open(full_tsv, encoding="utf-8") as f:
        next(f)  # skip header
        for line in f:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 2:
                continue
            path, cn = parts[0], parts[1].replace("\\n", "\n").replace("\\t", "\t")
            entries.append((path, cn))

    # Build Lua
    missing = 0
    out_lines = [
        "-- AUTO-GENERATED by build_speech_lua.py — do not edit by hand",
        "GLOBAL.setfenv(1, GLOBAL)",
        "local set_str = rawget(_G, \"dangtien_viet_set_str\")",
        f'local CHAR = "STRINGS.CHARACTERS.{char_key}"',
        "if not set_str or not STRINGS.CHARACTERS or not STRINGS.CHARACTERS." + char_key + " then",
        f'    print("[DangTienVN] {char_key} not loaded — speech translation skipped")',
        "    return",
        "end",
        "",
    ]
    for path, cn in entries:
        vn = vn_map.get(cn)
        if vn is None:
            missing += 1
            continue
        # Convert path: "ACTIONFAIL.APPRAISE.NOTNOW" → STRINGS.CHARACTERS.XD_WUKONG.ACTIONFAIL.APPRAISE.NOTNOW
        # array indices like FOO[3] need adjustment
        out_lines.append(f'set_str(CHAR .. ".{path}", "{lua_escape(vn)}")')

    out_lines.append("")
    out_lines.append(f'print("[DangTienVN] {char_key} speech: {len(entries) - missing} translated, {missing} missing")')

    with open(out_lua, "w", encoding="utf-8") as f:
        f.write("\n".join(out_lines))
    print(f"Wrote {len(entries) - missing} entries → {out_lua} (missing: {missing})")


if __name__ == "__main__":
    main()
