-- Phase 2: STRINGS overrides cho NAMES, RECIPE_DESC, ACTIONS, SKIN_*, UI...
-- Dịch dựa trên scanner.txt + wiki_glossary.lua (canonical names từ PDF).
-- Total: ~939 entries

local _G = GLOBAL
GLOBAL.setfenv(1, GLOBAL)
local set_str = rawget(_G, "dangtien_viet_set_str")
if not set_str then return end

local s = set_str

-- =========================================================================
-- ACTIONS (~72)
-- =========================================================================
s("STRINGS.ACTIONS.ACTIVATE.XD_SHUOHUO", "Thu hoạch")
s("STRINGS.ACTIONS.BLINK.DUNZOU", "Độn tẩu")
s("STRINGS.ACTIONS.CASTAOE.XD_SJ_BGLXP", "Thi triển Thâu Nạp Thần Thông")
s("STRINGS.ACTIONS.CASTAOE.XD_SJ_XSYDZ", "Điểm hoá ngoan thạch")
s("STRINGS.ACTIONS.CASTAOE.XD_YUNXIAO_HYJDITEM", "Thi triển Không Gian Thần Thông")
s("STRINGS.ACTIONS.CASTSPELL.XD_KEEPDRY", "Giữ khô ráo")
s("STRINGS.ACTIONS.CLOSESPELLBOOK.XD_GUANBI", "Hủy bỏ")
s("STRINGS.ACTIONS.DEPLOY.XD_LUOSHEN_JIHUAZE", "Đặt cạm bẫy")
s("STRINGS.ACTIONS.GIVE.XD_ACTIVE", "Kích hoạt")
s("STRINGS.ACTIONS.GIVE.XD_CHONGNENG", "Sạc năng")
s("STRINGS.ACTIONS.GIVE.XD_FISH", "Thả")
s("STRINGS.ACTIONS.GIVE.XD_GCSZ", "Kích hoạt Cổ Truyền Tống Trận")
s("STRINGS.ACTIONS.GIVE.XD_JIQU", "Hấp thu linh khí")
s("STRINGS.ACTIONS.GIVE.XD_JITAN", "Kích hoạt đàn tế")
s("STRINGS.ACTIONS.GIVE.XD_LINGLI", "Bổ sung linh lực")
s("STRINGS.ACTIONS.GIVE.XD_REPAIR", "Sửa chữa")
s("STRINGS.ACTIONS.GIVE.XD_SHOUHUI", "Thu hồi")
s("STRINGS.ACTIONS.GIVE.XD_TIANCHONG", "Lấp đầy")
s("STRINGS.ACTIONS.JINGWEI_MAPBLINK", "Phi việt")
s("STRINGS.ACTIONS.SHIJI_DUNRU", "Pháp Thể Độn Nhập")
s("STRINGS.ACTIONS.USESPELLBOOK.XD_SHIFA", "Thi pháp")
s("STRINGS.ACTIONS.WONKEY_BIANSHEN", "Biến hoá")
s("STRINGS.ACTIONS.XD_FUR_COOK", "Luyện chế")
s("STRINGS.ACTIONS.XD_JIANGRENACTION.SHESHENG", "Xả sinh")
s("STRINGS.ACTIONS.XD_LC_PLANT", "Trồng")
s("STRINGS.ACTIONS.XD_LINGJIACTION.ATTACK", "Linh Kỹ")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.ADD_MASTER", "Đặt làm điểm chính")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.CHUMO", "Chạm")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.CLOSE", "Đóng")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.DUANZAO", "Rèn trang bị")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.DUNRU", "Độn nhập")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.EAT", "Ăn")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.FISH", "Câu")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.GET_FOOD", "Nhận triều cống")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.GUIRUI", "Quy nhụy")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.JIHUO", "Kích hoạt")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.JINRU", "Vào")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.JIQU", "Hấp thu linh lực")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.KLS", "Pháp Thể Độn Nhập")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.LIANHUA", "Luyện hoá")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.MAP", "Xem bản đồ")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.NAQU", "Lấy xuống")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.NIESUI", "Bóp vỡ")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.OPEN", "Mở")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.REMOVE_MASTER", "Huỷ điểm chính")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.SHESHENG", "Xả sinh")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.SHOUHUI", "Thu hồi")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.SJC", "Triệu Thực Kim Trùng")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.SUMMON", "Triệu hồi")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.SUMMON_LB", "Thi triển Huyền Bảo Thần Thông")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.SWHS", "Ngưng Thần")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.TRADE", "Giao dịch")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.TSMD_SWAP", "Đổi")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.TSMD_USE", "Huyễn hoá")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.USE", "Sử dụng")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.USE_GCSZ", "Truyền tống")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.XTLB_CLOSE", "Thu hồi thần thức")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.XTLB_OPEN", "Thần thức tham xét")
s("STRINGS.ACTIONS.XD_LUOSHEN_YIN_MAP.XYZZ", "Triệu Huyết Ngọc Châu")
s("STRINGS.ACTIONS.XD_PICK_PLANT", "Thu hoạch")
s("STRINGS.ACTIONS.XD_QISHUACTION", "Kỳ Thuật")
s("STRINGS.ACTIONS.XD_RESKIN", "Đổi skin")
s("STRINGS.ACTIONS.XD_TXTELE", "Chọn điểm truyền")
s("STRINGS.ACTIONS.XD_YUNYANG", "Linh lực ôn dưỡng")
s("STRINGS.ACTIONS.XS_HUAPENACTIONS", "Thêm")
s("STRINGS.ACTIONS.XS_JILIAN", "Tế luyện")
s("STRINGS.ACTIONS.XS_JILIAN10", "Tế luyện")
s("STRINGS.ACTIONS.XS_PET_LEVELUP.REPAIR", "Thôn phệ")
s("STRINGS.ACTIONS.XS_PET_LEVELUP.RONGHE", "Dung hợp")
s("STRINGS.ACTIONS.XS_WEAPON_REPAIR", "Bổ sung linh lực")
s("STRINGS.ACTIONS.XS_WEAPON_WENYANG", "Ôn dưỡng")
s("STRINGS.ACTIONS.YUNXIAO_DUNZOU", "Độn tẩu")

-- =========================================================================
-- CHARACTER_DESCRIPTIONS / NAMES / QUOTES / TITLES / SURVIVABILITY (~45)
-- =========================================================================
s("STRINGS.CHARACTER_DESCRIPTIONS.xd_hantianzun", "*Hải ngoại tán tu Lệ Phi Vũ")
s("STRINGS.CHARACTER_DESCRIPTIONS.xd_jingwei", "*Đi cùng Huyền Điểu")
s("STRINGS.CHARACTER_DESCRIPTIONS.xd_longtaizi", "*Yêu thích mùa đông")
s("STRINGS.CHARACTER_DESCRIPTIONS.xd_luoshen", "*Có thể trồng hoa Lạc Thần")
s("STRINGS.CHARACTER_DESCRIPTIONS.xd_shiji", "*Có thể sai khiến thạch tôm")
s("STRINGS.CHARACTER_DESCRIPTIONS.xd_sudaji", "*Thỉnh thoảng toả ra yêu khí")
s("STRINGS.CHARACTER_DESCRIPTIONS.xd_wangmazi", "*Cửu Tinh Cổ Thần")
s("STRINGS.CHARACTER_DESCRIPTIONS.xd_wukong", "*Đầu đội Khẩn Cô Chú")
s("STRINGS.CHARACTER_DESCRIPTIONS.xd_yunxiao", "*Vân Tiêu thông tuệ khéo tay")
s("STRINGS.CHARACTER_NAMES.xd_hantianzun", "Hàn Thiên Tôn")
s("STRINGS.CHARACTER_NAMES.xd_jingwei", "Tinh Vệ")
s("STRINGS.CHARACTER_NAMES.xd_longtaizi", "Long Thái Tử")
s("STRINGS.CHARACTER_NAMES.xd_luoshen", "Lạc Thần")
s("STRINGS.CHARACTER_NAMES.xd_shiji", "Thạch Cơ Nương Nương")
s("STRINGS.CHARACTER_NAMES.xd_sudaji", "Tô Đát Kỷ")
s("STRINGS.CHARACTER_NAMES.xd_wangmazi", "Vương Ma Tử")
s("STRINGS.CHARACTER_NAMES.xd_wukong", "Tôn Ngộ Không")
s("STRINGS.CHARACTER_NAMES.xd_yunxiao", "Tam Tiêu Nương Nương")
s("STRINGS.CHARACTER_QUOTES.xd_hantianzun", '"Ta là Hoàng Phong Cốc, Lệ Phi Vũ, không đáng kể."')
s("STRINGS.CHARACTER_QUOTES.xd_jingwei", '"Không tích lũy bước nhỏ, sao đến được ngàn dặm"')
s("STRINGS.CHARACTER_QUOTES.xd_longtaizi", '"Bản Thái Tử yêu nhất là tuyết băng giá lạnh."')
s("STRINGS.CHARACTER_QUOTES.xd_luoshen", '"Tàn úa… cũng là khởi đầu của tân sinh."')
s("STRINGS.CHARACTER_QUOTES.xd_shiji", '"Còn núi xanh, lo gì không có củi đốt"')
s("STRINGS.CHARACTER_QUOTES.xd_sudaji", '"Thiếp thân cuối cùng cũng thành người trong cuộc."')
s("STRINGS.CHARACTER_QUOTES.xd_wangmazi", '"Thuận là phàm, nghịch tức tiên"')
s("STRINGS.CHARACTER_QUOTES.xd_wukong", '"Lão Tôn ta đến đây!"')
s("STRINGS.CHARACTER_QUOTES.xd_yunxiao", '"Hỗn Nguyên Kim Đấu, mở!"')
s("STRINGS.CHARACTER_SURVIVABILITY.xd_hantianzun", "Tử lý đào sinh")
s("STRINGS.CHARACTER_SURVIVABILITY.xd_jingwei", "Thủ đáo cầm lai")
s("STRINGS.CHARACTER_SURVIVABILITY.xd_longtaizi", "Như cá gặp nước")
s("STRINGS.CHARACTER_SURVIVABILITY.xd_luoshen", "Gai góc tùng sinh")
s("STRINGS.CHARACTER_SURVIVABILITY.xd_shiji", "Gai góc khắp đường")
s("STRINGS.CHARACTER_SURVIVABILITY.xd_sudaji", "Du nhận hữu dư")
s("STRINGS.CHARACTER_SURVIVABILITY.xd_wangmazi", "Nghịch phong ác lãng")
s("STRINGS.CHARACTER_SURVIVABILITY.xd_wukong", "Dễ như trở bàn tay")
s("STRINGS.CHARACTER_SURVIVABILITY.xd_yunxiao", "Dễ như nhặt cỏ")
s("STRINGS.CHARACTER_TITLES.xd_hantianzun", "Thiên Nam Đệ Nhất Kiếm Tu")
s("STRINGS.CHARACTER_TITLES.xd_jingwei", "Yêu nữ của Viêm Đế")
s("STRINGS.CHARACTER_TITLES.xd_longtaizi", "Long Tộc Thánh Tử")
s("STRINGS.CHARACTER_TITLES.xd_luoshen", "Con gái của Phục Hi")
s("STRINGS.CHARACTER_TITLES.xd_shiji", "Yêu Tiên Triệt Giáo")
s("STRINGS.CHARACTER_TITLES.xd_sudaji", "Tuyệt Đại Yêu Phi")
s("STRINGS.CHARACTER_TITLES.xd_wangmazi", "Ma Đầu")
s("STRINGS.CHARACTER_TITLES.xd_wukong", "Thiên Mệnh Nhân")
s("STRINGS.CHARACTER_TITLES.xd_yunxiao", "Đệ tử ngoại môn Triệt Giáo")

-- =========================================================================
-- FBJILIANTSR (8) — Tế luyện thông báo
-- =========================================================================
s("STRINGS.FBJILIANTSR.INCD", "Cần thời gian điều chỉnh linh lực trong cơ thể")
s("STRINGS.FBJILIANTSR.JILIAN", "Tế luyện")
s("STRINGS.FBJILIANTSR.JLLEVEL", "Thần hồn ta đang run rẩy, đợi đến Nguyên Anh kỳ hãy thử lại")
s("STRINGS.FBJILIANTSR.KQJILIAN", "Khảm nhập Linh Bảo")
s("STRINGS.FBJILIANTSR.LSJILIAN", "Khảm nhập Linh Thạch")
s("STRINGS.FBJILIANTSR.NOBYSP", "Không đủ Thượng Phẩm Linh Thạch để tế luyện linh bảo")
s("STRINGS.FBJILIANTSR.NOLEVEL", "Cần đạt Nguyên Anh kỳ mới có thể điều khiển Huyền Bảo này")
s("STRINGS.FBJILIANTSR.NOTCURRENTOWNER", "Thần niệm của người khác trên Linh Bảo không thể xoá đi")

-- =========================================================================
-- NAMES (~403) — vật phẩm/sinh vật/công trình
-- =========================================================================
s("STRINGS.NAMES.FENCE_GATE_LUOSHEN", "Cẩm Môn")
s("STRINGS.NAMES.FENCE_GATE_LUOSHEN_ITEM", "Cẩm Môn")
s("STRINGS.NAMES.FENCE_LUOSHEN", "Hàng rào")
s("STRINGS.NAMES.FENCE_LUOSHEN_ITEM", "Hàng rào Phương Phỉ")
s("STRINGS.NAMES.SUDAJI_KILLED", "Nhục thân tiêu vong")
s("STRINGS.NAMES.TURF_JINGWEITILE", "Địa bì lấp biển")
s("STRINGS.NAMES.TURF_XDTILE1", "Địa bì Côn Bằng xanh tốt")
s("STRINGS.NAMES.TURF_XDTILE2", "Địa bì Côn Bằng linh mạch")
s("STRINGS.NAMES.TURF_XDTILE3", "Địa bì Côn Bằng ma hoá")
s("STRINGS.NAMES.WALL_LUOSHEN", "Tường thêu")
s("STRINGS.NAMES.WALL_LUOSHEN_ITEM", "Tường thêu")
s("STRINGS.NAMES.XD_AYHX", "Râu Bóng Tối")
s("STRINGS.NAMES.XD_AYMG", "Hoa Hồng Bóng Tối")
s("STRINGS.NAMES.XD_BACK_XH", "Huyền Hồ")
s("STRINGS.NAMES.XD_BAIHU", "Tàn thân Bạch Hổ")
s("STRINGS.NAMES.XD_BAIHU_SKIN", "Da hổ gấm")
s("STRINGS.NAMES.XD_BJMS", "Bách Kiếp Ma Thân")
s("STRINGS.NAMES.XD_BJMS_BUILDER", "Bách Kiếp Ma Thân")
s("STRINGS.NAMES.XD_BJMS_KL", "Ma Hài")
s("STRINGS.NAMES.XD_BJSJ", "Bất Tận Thần Kiếm")
s("STRINGS.NAMES.XD_BYSP", "Bổn Nguyên Toái Phiến")
s("STRINGS.NAMES.XD_CHOUJIANGJI", "Máy Quay Thưởng Linh Thạch")
s("STRINGS.NAMES.XD_CL", "Xích Long")
s("STRINGS.NAMES.XD_CRC", "Kho Thịt")
s("STRINGS.NAMES.XD_CWKJ_CONTAINER", "Không Gian Trữ Vật")
s("STRINGS.NAMES.XD_DANYAO_BG", "Bích Cốc Đan")
s("STRINGS.NAMES.XD_DANYAO_DT", "Đoán Thể Hoàn")
s("STRINGS.NAMES.XD_DANYAO_HJ", "Hoá Tinh Đan")
s("STRINGS.NAMES.XD_DANYAO_HL", "Hợp Linh Hoàn")
s("STRINGS.NAMES.XD_DANYAO_HS", "Hoá Thần Đan")
s("STRINGS.NAMES.XD_DANYAO_HY", "Hồi Nguyên Hoàn")
s("STRINGS.NAMES.XD_DANYAO_JQ", "Tụ Khí Hoàn")
s("STRINGS.NAMES.XD_DANYAO_JY", "Kết Anh Đan")
s("STRINGS.NAMES.XD_DANYAO_KX", "Khấu Hư Đan")
s("STRINGS.NAMES.XD_DANYAO_NS", "Ngưng Thần Hoàn")
s("STRINGS.NAMES.XD_DANYAO_RL", "Dung Linh Hoàn")
s("STRINGS.NAMES.XD_DANYAO_SM", "Sơ Mạch Hoàn")
s("STRINGS.NAMES.XD_DANYAO_XS", "Tẩy Tủy Hoàn")
s("STRINGS.NAMES.XD_DANYAO_YX", "Uẩn Huyết Hoàn")
s("STRINGS.NAMES.XD_DANYAO_YZ", "Vân Trung Đan")
s("STRINGS.NAMES.XD_DANYAO_ZJ", "Trúc Cơ Đan")
s("STRINGS.NAMES.XD_DBG", "Đa Bảo Các")
s("STRINGS.NAMES.XD_DC", "Đèn Trang Trí")
s("STRINGS.NAMES.XD_DEERCLOPS_ZIYUN", "Hồn phách Tinh Thể Độc Nhãn Cự Lộc")
s("STRINGS.NAMES.XD_DOOR_EXIT", "Lối ra")
s("STRINGS.NAMES.XD_DOOR_EXIT1", "Lối ra")

-- Đan dược cấp phẩm (Cấp 1-5)
local PIN = {"Nhất phẩm", "Nhị phẩm", "Tam phẩm", "Tứ phẩm", "Ngũ phẩm"}
local DAN_GROUPS = {
    {"XD_DY_CYFXD_", "Xích Dương Phần Huyết Đan"},
    {"XD_DY_DMHSD_", "Địa Mạch Hồi Sinh Đan"},
    {"XD_DY_HSPHD_", "Hàn Tủy Tỵ Hỏa Đan"},
    {"XD_DY_LMSQD_", "Lôi Minh Sát Khí Đan"},
    {"XD_DY_PSHSD_", "Bàn Thạch Hộ Thân Đan"},
    {"XD_DY_QJQSD_", "Thiên Cơ Xảo Thủ Đan"},
    {"XD_DY_QXDHD_", "Thanh Tâm Tẩy Hồn Đan"},
    {"XD_DY_XTTYD_", "Huyết Đào Thiết Nguyên Đan"},
    {"XD_DY_XYNYD_", "Huyền Dương Noãn Ngọc Đan"},
    {"XD_DY_YFSXD_", "Ngự Phong Thần Hành Đan"},
}
for _, g in ipairs(DAN_GROUPS) do
    for i = 1, 5 do
        s("STRINGS.NAMES." .. g[1] .. i, PIN[i] .. " " .. g[2])
    end
end
s("STRINGS.NAMES.XD_DY_FD", "Phế Đan")
s("STRINGS.NAMES.XD_DY_TSFHD", "Thế Tử Phản Hồn Đan")

s("STRINGS.NAMES.XD_FABAO", "Pháp Bảo mất linh tính")
s("STRINGS.NAMES.XD_FANHUNGUOPU", "Mứt Quả Phản Hồn")
s("STRINGS.NAMES.XD_FANHUNSHU", "Cây Phản Hồn")
s("STRINGS.NAMES.XD_FANHUNSHUVINE", "Dây Quả Phản Hồn")
s("STRINGS.NAMES.XD_FANSHENGXIANG", "Hương Phục Sinh")
s("STRINGS.NAMES.XD_FB_HOUND", "Hồn phách Hound")
s("STRINGS.NAMES.XD_FB_MUTATEDDEERCLOPS", "Hồn phách Tinh Thể Độc Nhãn Cự Lộc")
s("STRINGS.NAMES.XD_FB_MUTATEDHOUND", "Hồn phách Hound suy yếu")
s("STRINGS.NAMES.XD_FB_MUTATEDWARG", "Hồn phách Warg phụ thân")
s("STRINGS.NAMES.XD_FHG", "Quả Phản Hồn")
s("STRINGS.NAMES.XD_FHS_DESK", "Thanh Ngọc Án")
s("STRINGS.NAMES.XD_FHS_LIGHT", "Đèn Sáng")
s("STRINGS.NAMES.XD_FJ", "Phẫn Tịch")
s("STRINGS.NAMES.XD_FLOWER_BH", "Bách Hợp")
s("STRINGS.NAMES.XD_FLOWER_BMG", "Hồng Bạch")
s("STRINGS.NAMES.XD_FLOWER_LL", "Linh Lan")
s("STRINGS.NAMES.XD_FLOWER_MD", "Mẫu Đơn")
s("STRINGS.NAMES.XD_FLOWER_MLH", "Mộc Lê Hoa")
s("STRINGS.NAMES.XD_FLOWER_PGY", "Bồ Công Anh")
s("STRINGS.NAMES.XD_FLOWER_SFR", "Thủy Phù Dung")
s("STRINGS.NAMES.XD_FLOWER_YL", "U Lan")
s("STRINGS.NAMES.XD_FLOWER_ZYH", "Triều Dương Hoa")
s("STRINGS.NAMES.XD_FS", "Phượng Tủy")
s("STRINGS.NAMES.XD_FSCT", "Phục Sinh Từ Đài")
s("STRINGS.NAMES.XD_FTJ", "Phẫn Thiên Kiếm")
s("STRINGS.NAMES.XD_FTYS", "Chuồng Vôn Dương")
s("STRINGS.NAMES.XD_FUTU", "Ma Tướng Phù Đồ")
s("STRINGS.NAMES.XD_FUTU_SMALL", "Linh Khoáng Ma Ngẫu")
s("STRINGS.NAMES.XD_GCSZ", "Cổ Truyền Tống Trận")
s("STRINGS.NAMES.XD_GJ", "Giếng Ngọt")
s("STRINGS.NAMES.XD_GJX", "Hộp Dụng Cụ")
s("STRINGS.NAMES.XD_HANTIANZUN", "Hàn Thiên Tôn")
s("STRINGS.NAMES.XD_HE_CONTAINER", "Tai Khỉ")
s("STRINGS.NAMES.XD_HHLMZ", "Bàn Gỗ Hoàng Hoa Lý")
s("STRINGS.NAMES.XD_HJJM", "Hoá Kiếp Tiêm Mãng")
s("STRINGS.NAMES.XD_HMSW", "Nhà Cây Mèo Gấu Trúc")
s("STRINGS.NAMES.XD_HT", "Hạo Thiên Thượng Đế Pháp Thân")
s("STRINGS.NAMES.XD_HTZ_FJFB", "Phi Kiếm Phù Bảo")
s("STRINGS.NAMES.XD_HTZ_NOLQ", "Linh lực không đủ")
s("STRINGS.NAMES.XD_HTZ_NOWEAPON", "Cần cầm vũ khí chuyên dụng để sử dụng")
s("STRINGS.NAMES.XD_HTZ_QZJ", "Thanh Trúc Phong Vân Kiếm")
s("STRINGS.NAMES.XD_HTZ_QZXY", "Kỳ Châu Huyết Ngọc")
s("STRINGS.NAMES.XD_HTZ_SJC", "Thực Kim Trùng")
s("STRINGS.NAMES.XD_HTZ_SJCX", "Hộp Thực Kim Trùng")
s("STRINGS.NAMES.XD_HTZ_TLZ", "Thiên Lôi Tử")
s("STRINGS.NAMES.XD_HTZ_TXM", "Ngũ Tử Đồng Tâm Ma")
s("STRINGS.NAMES.XD_HTZ_XTD", "Hư Thiên Đỉnh")
s("STRINGS.NAMES.XD_HTZ_XYZZ", "Huyết Ngọc Châu")
s("STRINGS.NAMES.XD_HTZ_XYZZL", "Trứng Huyết Ngọc Châu")
s("STRINGS.NAMES.XD_HTZ_ZTP", "Chưởng Thiên Bình (Cô Phẩm)")
s("STRINGS.NAMES.XD_HUAPEN", "Bồn Hoa Uẩn Linh")
s("STRINGS.NAMES.XD_HXYP", "Hộ Tâm Ngọc Bội")
s("STRINGS.NAMES.XD_HYC", "Hồ Tẩy Nguyệt")
s("STRINGS.NAMES.XD_HYF", "Hỗn Nguyên Phủ")
s("STRINGS.NAMES.XD_ICEDRAGON", "Hàn Băng Linh Nhãn")
s("STRINGS.NAMES.XD_INFOBOOK", "Tu Tiên Mật Quyển")
s("STRINGS.NAMES.XD_JCBIRD", "Chu Điểu")
s("STRINGS.NAMES.XD_JCBIRD_SPITTER", "Hỏa Tinh")
s("STRINGS.NAMES.XD_JFSN", "Kim Phượng Thần Niệm")
s("STRINGS.NAMES.XD_JGB", "Kim Cô Bổng")
s("STRINGS.NAMES.XD_JINGWEI", "Tinh Vệ")
s("STRINGS.NAMES.XD_JINGWEI10", "Lông Vũ Mảnh")
s("STRINGS.NAMES.XD_JINGWEI_BLOWDART", "Huyền Vũ Xuy Tiễn")
s("STRINGS.NAMES.XD_JINGWEI_BLOWDART_SHADOW", "Huyền Điểu")
s("STRINGS.NAMES.XD_JINGWEI_FAN", "Thanh Xuất Ư Lam")
s("STRINGS.NAMES.XD_JINGWEI_FENICE1", "Huyền Điểu")
s("STRINGS.NAMES.XD_JINGWEI_FENICE2", "Huyền Điểu")
s("STRINGS.NAMES.XD_JINGWEI_FENICE3", "Huyền Điểu")
s("STRINGS.NAMES.XD_JINGWEI_FENICE4", "Huyền Điểu")
s("STRINGS.NAMES.XD_JINGWEI_FENICE_BUILDER", "Huyền Điểu")
s("STRINGS.NAMES.XD_JINGWEI_HAT", "Thúy Vũ Tiên Tung")
s("STRINGS.NAMES.XD_JINGWEI_ZZQL", "Chỉ Thử Thanh Lục")
s("STRINGS.NAMES.XD_JITAN", "Đàn Tế")
s("STRINGS.NAMES.XD_JL", "Kim Lân")
s("STRINGS.NAMES.XD_JUSHUWU", "Nhà Gỗ")
s("STRINGS.NAMES.XD_JWTCD", "Đèn Kim Ô Tung Thái")
s("STRINGS.NAMES.XD_KLXW", "Nhà Voi")
s("STRINGS.NAMES.XD_LBJLT", "Linh Bảo Tế Luyện Đài")
s("STRINGS.NAMES.XD_LBX", "Hòm Linh Bảo")
s("STRINGS.NAMES.XD_LC_CYH", "Xích Dương Hoa")
s("STRINGS.NAMES.XD_LC_CYH_SEED", "Hạt Xích Dương")
s("STRINGS.NAMES.XD_LC_DMS", "Địa Mạch Tham")
s("STRINGS.NAMES.XD_LC_DMS_SEED", "Hạt Địa Tủy")
s("STRINGS.NAMES.XD_LC_HSC", "Sương Hàn Thảo")
s("STRINGS.NAMES.XD_LC_HSC_SEED", "Hạt Phú Băng")
s("STRINGS.NAMES.XD_LC_LMG", "Lôi Minh Cốc")
s("STRINGS.NAMES.XD_LC_LMG_SEED", "Hạt Điện Khuẩn")
s("STRINGS.NAMES.XD_LC_QFX", "Thanh Phong Tụ")
s("STRINGS.NAMES.XD_LC_QFX_SEED", "Hạt Thanh Nang")
s("STRINGS.NAMES.XD_LC_YHH", "U Hồn Hoa")
s("STRINGS.NAMES.XD_LC_YHH_SEED", "Hạt U Ảnh")
s("STRINGS.NAMES.XD_LGZBH", "Hộp Trang Sức Lưu Quang")
s("STRINGS.NAMES.XD_LHWDC", "Long Hồn Vấn Đạo Chuỳ")
s("STRINGS.NAMES.XD_LIANDANLU", "Lò Đan")
s("STRINGS.NAMES.XD_LINGSHI1", "Hạ Phẩm Linh Thạch")
s("STRINGS.NAMES.XD_LINGSHI2", "Trung Phẩm Linh Thạch")
s("STRINGS.NAMES.XD_LINGSHI3", "Thượng Phẩm Linh Thạch")
s("STRINGS.NAMES.XD_LINGSHI4", "Cực Phẩm Linh Thạch")
s("STRINGS.NAMES.XD_LLBX", "Bảo Rương Linh Lung")
s("STRINGS.NAMES.XD_LLBX_CONTAINER", "Bảo Rương Linh Lung")
s("STRINGS.NAMES.XD_LONGTAIZI", "Long Thái Tử")
s("STRINGS.NAMES.XD_LONGZHU", "Long Châu")
s("STRINGS.NAMES.XD_LUOSHEN", "Lạc Thần")
s("STRINGS.NAMES.XD_LUOSHENZHU", "Lạc Thần Tru")
s("STRINGS.NAMES.XD_LUOSHENZHU_VINE", "Dây leo")
s("STRINGS.NAMES.XD_LUOSHENZHU_VINE_TAIL", "Dây leo")
s("STRINGS.NAMES.XD_LUOSHEN_DEATHFLOWER_BUILDER", "Diệt chi Hoa")
s("STRINGS.NAMES.XD_LUOSHEN_DINGHUNXIANGLU", "Định Hồn Hương Lư")
s("STRINGS.NAMES.XD_LUOSHEN_HUA", "Hoa Lạc Thần")
s("STRINGS.NAMES.XD_LUOSHEN_HUAXIA", "Hộp Hoa Lạc Thần")
s("STRINGS.NAMES.XD_LUOSHEN_HUAYIN", "Lạc Thần Hoa Nhân")
s("STRINGS.NAMES.XD_LUOSHEN_HUAZHONG", "Hạt Hoa Lạc Thần")
s("STRINGS.NAMES.XD_LUOSHEN_JIANGREN", "Giáng Nhận")
s("STRINGS.NAMES.XD_LUOSHEN_JIHUAZE", "Cức Hoa Trạch")
s("STRINGS.NAMES.XD_LUOSHEN_KRSS", "Khô Vinh Song Sinh")
s("STRINGS.NAMES.XD_LUOSHEN_LIFEFLOWER_BUILDER", "Sinh chi Hoa")
s("STRINGS.NAMES.XD_LUOSHEN_LIUGUANGHUAFEN", "Lưu Quang Hoa Phấn")
s("STRINGS.NAMES.XD_LUOSHEN_QINGSHU", "Lạc Thần Thanh Sơ")
s("STRINGS.NAMES.XD_LUOSHEN_YIN", "Lạc Thần Dẫn")
s("STRINGS.NAMES.XD_LUOXIANG_PENGROU", "Lạc Hương Phanh Nhục")
s("STRINGS.NAMES.XD_LYCX", "Tổ Long Nhặng")
s("STRINGS.NAMES.XD_LYD", "Liên Diệp Đông")
s("STRINGS.NAMES.XD_MG", "Hũ Mật")
s("STRINGS.NAMES.XD_MGLZ", "Giỏ Nấm")
s("STRINGS.NAMES.XD_MGQG", "Ma Quái Kiềm Cốt")
s("STRINGS.NAMES.XD_MO_BUILDER", "Ma Kiếm")
s("STRINGS.NAMES.XD_MR", "Mặc Nhiễm")
s("STRINGS.NAMES.XD_NL", "Nghịch Lân")
s("STRINGS.NAMES.XD_NPXSZ", "Niết Bàn Huyết Tủy Trúc")
s("STRINGS.NAMES.XD_PFLNW", "Nhà Bò Lông Dài")
s("STRINGS.NAMES.XD_PLANT_CYH", "Xích Dương Hoa")
s("STRINGS.NAMES.XD_PLANT_DMS", "Địa Mạch Tham")
s("STRINGS.NAMES.XD_PLANT_HSC", "Sương Hàn Thảo")
s("STRINGS.NAMES.XD_PLANT_LMG", "Lôi Minh Cốc")
s("STRINGS.NAMES.XD_PLANT_QFX", "Thanh Phong Tụ")
s("STRINGS.NAMES.XD_PLANT_YHH", "U Hồn Hoa")
s("STRINGS.NAMES.XD_POG", "Linh Hồ")
s("STRINGS.NAMES.XD_POG_HOUSE", "Thanh Khâu Phường")
s("STRINGS.NAMES.XD_POG_TAIL", "Đuôi Linh Hồ")
s("STRINGS.NAMES.XD_POISON_DAMAGE", "Trúng độc")
s("STRINGS.NAMES.XD_QFWJD", "Thiên Phiên Vạn Kiếp Đao")
s("STRINGS.NAMES.XD_QIANYU", "Lông Vũ Mảnh")
s("STRINGS.NAMES.XD_QLCH", "Tàn Hồn Kỳ Lân")
s("STRINGS.NAMES.XD_QLCH_FS", "Tàn Hồn Kỳ Lân")
s("STRINGS.NAMES.XD_QLJQ", "Quỳnh Lâu Kim Khuyết")
s("STRINGS.NAMES.XD_QLR", "Sừng Kỳ Lân")
s("STRINGS.NAMES.XD_QWSK", "Thực Khám Thiên Vị")
s("STRINGS.NAMES.XD_QXDX", "Thanh Tụ Đan Tiên")
s("STRINGS.NAMES.XD_QXDX_NPC", "Thanh Tụ Đan Tiên")
s("STRINGS.NAMES.XD_QXDX_TALKS.1", "Tiểu hữu lại lấy tinh hoa thiên địa, làm chuyện cặn bã!")
s("STRINGS.NAMES.XD_QXDX_TALKS.2", "Tiểu hữu, lão phu nơi đây có lẽ có vài loại đan dược ngươi cần")
s("STRINGS.NAMES.XD_QXDX_TALKS.3", "Cảm tạ tiểu hữu chiếu cố")
s("STRINGS.NAMES.XD_QXDX_TALKS.4", "Tiểu hữu, linh thạch của ngươi dường như không đủ rồi")
s("STRINGS.NAMES.XD_QXDX_TALKS.5", "Đại đạo như uyên, lối vào chỉ một sợi tơ. Lão phu hôm nay, lấy thân làm bè, tranh thêm một tia cơ duyên!")
s("STRINGS.NAMES.XD_QY", "Thanh Nguyệt")
s("STRINGS.NAMES.XD_ROCK1", "Mỏ Linh Thạch")
s("STRINGS.NAMES.XD_ROCK2", "Mỏ Linh Thạch Hiếm")
s("STRINGS.NAMES.XD_ROCK3", "Mỏ Linh Thạch Tuyệt Phẩm")
s("STRINGS.NAMES.XD_ROCK_BASALT", "Đá Huyền Vũ")
s("STRINGS.NAMES.XD_SANDBLOCK", "Hoãn Linh Tháp")
s("STRINGS.NAMES.XD_SGC", "Kho Rau Quả")
s("STRINGS.NAMES.XD_SHADOWSPIDERQUEEN", "Nhện Nữ Vương")
s("STRINGS.NAMES.XD_SHADOWSPIDER_DROPPER", "Huyệt Cư Huyền Chu")
s("STRINGS.NAMES.XD_SHADOWSPIDER_MOON", "Nhện Phá Giới")
s("STRINGS.NAMES.XD_SHATANGSHU", "Cây Sa Đường")
s("STRINGS.NAMES.XD_SHATANGSHUNUT", "Rễ Cây Sa Đường")
s("STRINGS.NAMES.XD_SHATANGSHUVINE", "Dây Quả Sa Đường")
s("STRINGS.NAMES.XD_SHATANGSHU_NORMAL", "Cây Sa Đường")
s("STRINGS.NAMES.XD_SHIJI", "Thạch Cơ Nương Nương")
s("STRINGS.NAMES.XD_SJ_BGLXP", "Bát Quái Long Tu Phách")
s("STRINGS.NAMES.XD_SJ_BGYGP", "Bát Quái Vân Quang Phách")
s("STRINGS.NAMES.XD_SJ_BY", "Bích Vân Đồng Tử")
s("STRINGS.NAMES.XD_SJ_BY_BUILDER", "Bích Vân Đồng Tử")
s("STRINGS.NAMES.XD_SJ_CY", "Thải Vân Đồng Tử")
s("STRINGS.NAMES.XD_SJ_CY_BUILDER", "Thải Vân Đồng Tử")
s("STRINGS.NAMES.XD_SJ_KLS", "Khô Lâu Sơn")
s("STRINGS.NAMES.XD_SJ_PYSK", "Bàn Nhạc Thạch Khôi")
s("STRINGS.NAMES.XD_SJ_ROCKY", "Thạch Tôm")
s("STRINGS.NAMES.XD_SJ_SXZ", "Thực Tâm Trụ")
s("STRINGS.NAMES.XD_SJ_TEJ", "Thái A Kiếm")
s("STRINGS.NAMES.XD_SJ_TLSQ", "Thông Linh Thạch Khiếu")
s("STRINGS.NAMES.XD_SJ_XSYDZ", "Tỉnh Thạch Yết Đạo Trượng")
s("STRINGS.NAMES.XD_SKELETON", "Bộ Xương")
s("STRINGS.NAMES.XD_SLY", "Thủy Long Ngâm")
s("STRINGS.NAMES.XD_SOUL_WOLF", "Hồn Lang")
s("STRINGS.NAMES.XD_SPIDER", "Yêu Trá Ma Châu")
s("STRINGS.NAMES.XD_SPIDERDEN", "Hang Ma Châu")
s("STRINGS.NAMES.XD_SPIDERQUEEN", "Tà Sát Châu Vương")
s("STRINGS.NAMES.XD_SPIDER_LEG", "Tà Sát Bộ Túc")
s("STRINGS.NAMES.XD_SSKL", "Thần Thức Khôi Lỗi")
s("STRINGS.NAMES.XD_STG", "Quả Sa Đường")
s("STRINGS.NAMES.XD_STOOL", "Thừa Vận Tọa")
s("STRINGS.NAMES.XD_SUDAJI", "Tô Đát Kỷ")
s("STRINGS.NAMES.XD_SUDAJI_MXRG", "Mai Hương Như Cố")
s("STRINGS.NAMES.XD_SUDAJI_REDLANTERN", "Đăng Ngư Long")
s("STRINGS.NAMES.XD_SUDAJI_SJPN", "Bội Nang Bách Vị")
s("STRINGS.NAMES.XD_SUDAJI_SJPN_CONTAINER", "Bội Nang Bách Vị")
s("STRINGS.NAMES.XD_SUDAJI_SOUL", "Mảnh Nguyên Thần Yêu Thú")
s("STRINGS.NAMES.XD_SUDAJI_TSMD", "Mộc Điêu Thế Thân")
s("STRINGS.NAMES.XD_SUDAJI_YHLY", "Dưỡng Hồn Linh Ngọc")
s("STRINGS.NAMES.XD_SUDAJI_YWFH", "Nhất Vũ Phương Hoa")
s("STRINGS.NAMES.XD_SWHS", "Thân Ngoại Hoá Thân")
s("STRINGS.NAMES.XD_SWHS_LEVELUP", "Thân Ngoại Hoá Thân (Hoàng Cân Lực Sĩ)")
s("STRINGS.NAMES.XD_SWHS_LEVELUPWMZ", "Thân Ngoại Hoá Thân (Lục Mặc Phân Thân)")
s("STRINGS.NAMES.XD_TIANJIWU", "Thiên Cơ Ốc")
s("STRINGS.NAMES.XD_TIANJI_JUANZHOU", "Thiên Cơ Quyển Trục")
s("STRINGS.NAMES.XD_TIANJI_LINGPAI", "Thiên Cơ Lệnh Bài")
s("STRINGS.NAMES.XD_TIMELEFT", "Hồi chiêu còn %d giây")
s("STRINGS.NAMES.XD_TREE_DF", "Đan Phong")
s("STRINGS.NAMES.XD_TREE_LS", "Lam Sam")
s("STRINGS.NAMES.XD_TREE_XHS", "Hạnh Hoa Thụ")
s("STRINGS.NAMES.XD_TREE_YHS", "Cây Anh Đào")
s("STRINGS.NAMES.XD_TREE_YLS", "Yên Liễu Thụ")
s("STRINGS.NAMES.XD_TREE_YXS", "Ngân Hạnh")
s("STRINGS.NAMES.XD_TSSYQ", "Thiên Thú Thực Nguyên Thương")
s("STRINGS.NAMES.XD_WANGMAZI", "Vương Ma Tử")
s("STRINGS.NAMES.XD_WMZ_DB", "Đậu Binh Khôi Lỗi")
s("STRINGS.NAMES.XD_WMZ_KJB", "Khôn Cực Tiên")
s("STRINGS.NAMES.XD_WMZ_MD1", "Mộc Điêu Warg phụ thân")
s("STRINGS.NAMES.XD_WMZ_MD2", "Mộc Điêu Kim Phượng")
s("STRINGS.NAMES.XD_WMZ_MD3", "Mộc Điêu Cự Lộc")
s("STRINGS.NAMES.XD_WMZ_MD4", "Mộc Điêu Long Nhặng")
s("STRINGS.NAMES.XD_WMZ_MD5", "Mộc Điêu Mi Lộc Nga")
s("STRINGS.NAMES.XD_WMZ_MD6", "Mộc Điêu Kỳ Lân")
s("STRINGS.NAMES.XD_WMZ_MD7", "Mộc Điêu Hùng Hoan")
s("STRINGS.NAMES.XD_WMZ_MD8", "Mộc Điêu Viễn Cổ Chức Ảnh Giả")
s("STRINGS.NAMES.XD_WMZ_SLXJ", "Sát Lục Tiên Quyết")
s("STRINGS.NAMES.XD_WMZ_TNZ", "Thiên Nghịch Châu")
s("STRINGS.NAMES.XD_WMZ_TNZ_CHGZ", "Thúy Hà Quang Trản")
s("STRINGS.NAMES.XD_WMZ_TNZ_FTL", "Phục Long Đài")
s("STRINGS.NAMES.XD_WMZ_XSJ", "Huyết Sát Kiếm")
s("STRINGS.NAMES.XD_WMZ_ZHF", "Tôn Hồn Phiên (Cô Phẩm)")
s("STRINGS.NAMES.XD_WMZ_ZHF_GROUND", "Tôn Hồn Phiên (Cô Phẩm)")
s("STRINGS.NAMES.XD_WMZ_ZHF_SOUL", "Hồn Linh Tôn Hồn Phiên")
s("STRINGS.NAMES.XD_WS", "Vấn Thế")
s("STRINGS.NAMES.XD_WSJX", "Hộp Kiếm Vô Song")
s("STRINGS.NAMES.XD_WUKONG", "Tôn Ngộ Không")
s("STRINGS.NAMES.XD_WUKONG_DSMO", "Đại Thánh Mộc Ngẫu")
s("STRINGS.NAMES.XD_WUKONG_JGB", "Như Ý Kim Cô Bổng")
s("STRINGS.NAMES.XD_WUKONG_PHANTOM", "Tôn Ngộ Không")
s("STRINGS.NAMES.XD_WUKONG_SHADOW", "Tôn Ngộ Không")
s("STRINGS.NAMES.XD_WXJ", "Vô Tướng Kiếm")
s("STRINGS.NAMES.XD_WYJ", "Vong Ưu Kiếm")
s("STRINGS.NAMES.XD_XCDF", "Tinh Tế Đan Phủ")
s("STRINGS.NAMES.XD_XHWYJ", "Hạnh Hoa Vi Vũ Kiếm")
s("STRINGS.NAMES.XD_XIANHE", "Tiên Hạc")
s("STRINGS.NAMES.XD_XIANJIAN_BUILDER", "Tiên Kiếm")
s("STRINGS.NAMES.XD_XINMO", "Tâm Ma")
s("STRINGS.NAMES.XD_XJCGD", "Tiêu Kim Xích Cốt Đao")
s("STRINGS.NAMES.XD_XJS", "Phù Dung Huyền Cơ Tản")
s("STRINGS.NAMES.XD_XLJ", "Tinh La Kiếm")
s("STRINGS.NAMES.XD_XSHJ", "Tà Sát Hộ Giáp")
s("STRINGS.NAMES.XD_XTBH", "Huyền Thiên Bảo Hồ")
s("STRINGS.NAMES.XD_XTZLJ_STR", "Có thể dùng một lần trong khi chuyên vũ thần thông duy trì")
s("STRINGS.NAMES.XD_XUANYU", "Huyền Vũ")
s("STRINGS.NAMES.XD_YHBS", "Dưỡng Hồn Tỉ Thủ")
s("STRINGS.NAMES.XD_YHSYZ", "Nguyệt Hoa Thập Dược Chi")
s("STRINGS.NAMES.XD_YLXC", "Ngọc Lộ Huyền Cang")
s("STRINGS.NAMES.XD_YLXQ", "Ngọc Lộ Tiên Khê")
s("STRINGS.NAMES.XD_YUNXIAO", "Tam Tiêu Nương Nương")
s("STRINGS.NAMES.XD_YUNXIAO_CHANGE.0.1", "Không vui vì vật, không buồn vì mình, là pháp môn thành tựu trường sinh tiên tôn")
s("STRINGS.NAMES.XD_YUNXIAO_CHANGE.0.2", "Tâm như chỉ thủy, tĩnh như an lan, đạo pháp tự nhiên.")
s("STRINGS.NAMES.XD_YUNXIAO_CHANGE.1.1", "Bản tiên đặc biệt yêu kẻ chân thực không hư danh.")
s("STRINGS.NAMES.XD_YUNXIAO_CHANGE.1.2", "Hành trên đường mà ứng tại tâm…")
s("STRINGS.NAMES.XD_YUNXIAO_CHANGE.2.1", "Đánh một trận sẽ biết bản tiên cô há phải hư danh.")
s("STRINGS.NAMES.XD_YUNXIAO_CHANGE.2.2", "Lĩnh giáo thủ đoạn của bản tiên cô đi.")
s("STRINGS.NAMES.XD_YUNXIAO_FGFQ", "Phù Cốt Pháp Khí")
s("STRINGS.NAMES.XD_YUNXIAO_FLS", "Phược Long Tỏa")
s("STRINGS.NAMES.XD_YUNXIAO_FYSZ", "Phức Uẩn Thủ Trượng")
s("STRINGS.NAMES.XD_YUNXIAO_HYJD", "Hỗn Nguyên Kim Đấu")
s("STRINGS.NAMES.XD_YUNXIAO_HYJDITEM", "Hỗn Nguyên Kim Đấu")
s("STRINGS.NAMES.XD_YUNXIAO_HYJDYQD", "Điểm Dịch Chuyển Hỗn Nguyên Kim Đấu")
s("STRINGS.NAMES.XD_YUNXIAO_HYTX", "Đài Dịch Chuyển Hỗn Nguyên Thái Hư")
s("STRINGS.NAMES.XD_YUNXIAO_JJJ", "Kim Giao Tiễn")
s("STRINGS.NAMES.XD_YUNXIAO_PORTABLE_SPICER", "Trạm Gia Vị Vân Yên")
s("STRINGS.NAMES.XD_YUNXIAO_YMSZ", "Vân Mạc Thượng Trang")
s("STRINGS.NAMES.XD_ZCMJ", "Tử Sát Diện Giáp")
s("STRINGS.NAMES.XD_ZCMY", "Tử Sát Ma Vũ")
s("STRINGS.NAMES.XD_ZCYSEED", "Túy Mai")
s("STRINGS.NAMES.XD_ZHF", "Tôn Hồn Phiên")
s("STRINGS.NAMES.XD_ZHOUWANG", "Trụ Vương")
s("STRINGS.NAMES.XD_ZHOUWANG_SHADOW", "Trụ Vương Pháp Thân")
s("STRINGS.NAMES.XD_ZIYUNBOSS", "Tử Vân Ma Quân")
s("STRINGS.NAMES.XD_ZIYUNBOSS_CHANNELER", "Ma Tâm Tử Vân")
s("STRINGS.NAMES.XD_ZIYUNBOSS_TALKS.1", "Có vài phần thực lực, dùng huyền bảo của bản quân thử ngươi xem nào.")
s("STRINGS.NAMES.XD_ZIYUNBOSS_TALKS.2", "Có thể bức bản quân đến mức này, quả là kẻ kinh tài tuyệt diễm.")
s("STRINGS.NAMES.XD_ZIYUNBOSS_TALKS.3", "Bản quân… cư nhiên… bại rồi…")
s("STRINGS.NAMES.XD_ZIYUNBOSS_TALKS.4.1", "Lũ kiến cỏ cũng dám quấy nhiễu sự thanh tịnh của bản quân!")
s("STRINGS.NAMES.XD_ZIYUNBOSS_TALKS.4.2", "Tán xương rải tro ngươi chỉ là việc nhẹ tay của bản quân.")
s("STRINGS.NAMES.XD_ZIYUNBOSS_TALKS.4.3", "Tiểu nhân vật không biết trời cao đất dày, bản quân vô cùng không thích!")
s("STRINGS.NAMES.XD_ZIYUNGE", "Tử Vân Các")
s("STRINGS.NAMES.XD_ZIYUNNPC_TALKS.1", "Đạo hữu phương nào đến đây, có thể giúp bản tôn chém đứt ma tướng trong tâm chăng?")
s("STRINGS.NAMES.XD_ZIYUNNPC_TALKS.2", "Tiểu hữu có thể giúp bản quân đánh bại hoá thân thất khống không, bản quân ắt sẽ trọng tạ!")
s("STRINGS.NAMES.XD_ZIYUNNPC_TALKS.3", "Đa tạ tiểu hữu, đây là chút lễ vật cảm tạ của bản quân.")
s("STRINGS.NAMES.XD_ZIYUNNPC_TALKS.4", "Khi nhàn bộ xin chớ làm phiền bản quân.")
s("STRINGS.NAMES.XD_ZIYUNNPC_TALKS.5", "Ma niệm trong tâm ngày càng khó áp chế.")
s("STRINGS.NAMES.XD_ZIYUNNPC_TALKS.6", "Với thủ đoạn của bản quân cũng không trấn áp được con côn bằng che trời này.")
s("STRINGS.NAMES.XD_ZIYUN_HOUSE", "Thiên Cơ Ốc Dị Hoá")
s("STRINGS.NAMES.XD_ZTP", "Chưởng Thiên Bình")
s("STRINGS.NAMES.XD_ZUICHUNYAN", "Túy Xuân Yên")
s("STRINGS.NAMES.XD_ZUICHUNYAN_SAPLING", "Cây Con Túy Xuân Yên")
s("STRINGS.NAMES.XD_ZYG_DESK", "Bàn")
s("STRINGS.NAMES.XD_ZYG_LIGHT", "Đèn")
s("STRINGS.NAMES.XD_ZYG_LIGHT1", "Đèn")
s("STRINGS.NAMES.XD_ZYG_NPC", "Tử Vân Ma Quân")
s("STRINGS.NAMES.XD_ZZXHCX", "Ổ Hùng Hoan Trang Giáp")

-- =========================================================================
-- PRETRANSLATED (chinese language picker — keep as-is)
-- =========================================================================
-- These are CN/Korean prompts asking to switch language; safe to leave.

-- =========================================================================
-- RECIPE_DESC (~113)
-- =========================================================================
s("STRINGS.RECIPE_DESC.FENCE_GATE_LUOSHEN_ITEM", "Cổng làm từ cánh hoa")
s("STRINGS.RECIPE_DESC.FENCE_LUOSHEN_ITEM", "Hàng rào làm từ cánh hoa")
s("STRINGS.RECIPE_DESC.TURF_JINGWEITILE", "Có thể dùng để lấp biển tạo đất")
s("STRINGS.RECIPE_DESC.WALL_LUOSHEN_ITEM", "Tường làm từ cánh hoa")
s("STRINGS.RECIPE_DESC.XD_BACK_XH", "Quả bầu có dung lượng nhất định")
s("STRINGS.RECIPE_DESC.XD_BJMS_BUILDER", "Thần thông ma đạo Phản Hư kỳ")
s("STRINGS.RECIPE_DESC.XD_CRC", "Linh khí trong kho thịt giúp thực phẩm dần khôi phục độ tươi")
s("STRINGS.RECIPE_DESC.XD_DBG", "Kệ trưng bày những vật phẩm hi thế của tu sĩ")
s("STRINGS.RECIPE_DESC.XD_DC", "Có thể phát ra ánh sáng yếu")
s("STRINGS.RECIPE_DESC.XD_FLOWER_BH", "Bếp núc lẫn anh đào măng cùng tiến, không bằng cánh hoa từng cánh thơm")
s("STRINGS.RECIPE_DESC.XD_FLOWER_BMG", "Mẫu đơn giả vô vọng ghen tị, hồng bạch xấu hổ không dám nở")
s("STRINGS.RECIPE_DESC.XD_FLOWER_LL", "Hoa linh lan đẹp như ngọc")
s("STRINGS.RECIPE_DESC.XD_FLOWER_MD", "Quốc sắc say men sớm, thiên hương nhuộm áo đêm")
s("STRINGS.RECIPE_DESC.XD_FLOWER_MLH", "Mộc lê nở thì hương đầy cành, hoa điền tan tác ngọc tham sai")
s("STRINGS.RECIPE_DESC.XD_FLOWER_PGY", "Hoa tựa nhung bông")
s("STRINGS.RECIPE_DESC.XD_FLOWER_SFR", "Thanh thuỷ xuất phù dung, thiên nhiên khử điêu trác")
s("STRINGS.RECIPE_DESC.XD_FLOWER_YL", "Cô lan sinh u viên, chúng thảo cùng vu một")
s("STRINGS.RECIPE_DESC.XD_FLOWER_ZYH", "Không có liễu nhung gió thổi, chỉ có hướng dương nghiêng về mặt trời")
s("STRINGS.RECIPE_DESC.XD_FTJ", "Phẫn Thiên Kiếm")
s("STRINGS.RECIPE_DESC.XD_FTYS", "Một chuồng dê hơi ghê rợn")
s("STRINGS.RECIPE_DESC.XD_GJ", "Có thể dùng để múc nước đầy bình")
s("STRINGS.RECIPE_DESC.XD_GJX", "Dùng để chứa các loại công cụ")
s("STRINGS.RECIPE_DESC.XD_HHLMZ", "Thức ăn đặt vào nhờ linh lực bảo quản chậm khôi phục độ tươi")
s("STRINGS.RECIPE_DESC.XD_HJJM", "Có thể giúp tránh một phần lôi kiếp")
s("STRINGS.RECIPE_DESC.XD_HMSW", "Nhà mèo công phu tinh xảo")
s("STRINGS.RECIPE_DESC.XD_HTZ_SJCX", "Có thể triệu hồi Thực Kim Trùng")
s("STRINGS.RECIPE_DESC.XD_HTZ_TLZ", "Vật liệu cực kỳ quý hiếm nhưng uy lực phi phàm")
s("STRINGS.RECIPE_DESC.XD_HTZ_XYZZL", "Cảm nhận được huyết khí cuộn trào trong đó")
s("STRINGS.RECIPE_DESC.XD_HUAPEN", "Bồn Hoa Uẩn Linh")
s("STRINGS.RECIPE_DESC.XD_HYC", "Tẩy rửa minh nguyệt, nuôi dưỡng linh ngư")
s("STRINGS.RECIPE_DESC.XD_JINGWEI_BLOWDART", "Phi tiêu công năng kỳ lạ")
s("STRINGS.RECIPE_DESC.XD_JINGWEI_FAN", "Một cây quạt thực dụng tinh xảo")
s("STRINGS.RECIPE_DESC.XD_JINGWEI_FENICE_BUILDER", "Cũng coi là vật trân quý hiếm có")
s("STRINGS.RECIPE_DESC.XD_JINGWEI_HAT", "Vật giữ ấm chống nước như than gửi giữa tuyết")
s("STRINGS.RECIPE_DESC.XD_JWTCD", "Đèn Kim Ô có thể chiếu sáng phạm vi nhất định")
s("STRINGS.RECIPE_DESC.XD_KLXW", "Nhà cho voi cư trú")
s("STRINGS.RECIPE_DESC.XD_LBJLT", "Có thể nhờ đó thử tế luyện Huyền Thiên Linh Bảo")
s("STRINGS.RECIPE_DESC.XD_LBX", "Bảo rương có linh tính, mỗi thế giới chỉ đặt được 3 cái")
s("STRINGS.RECIPE_DESC.XD_LGZBH", "Có thể chứa các loại bảo thạch trừ Bảo Thạch Cầu Vồng")
s("STRINGS.RECIPE_DESC.XD_LIANDANLU", "Vật luyện ra từ đây sẽ không phải hàng phàm")
s("STRINGS.RECIPE_DESC.XD_LUOSHEN_DEATHFLOWER_BUILDER", "Chuyển hoá thành Diệt chi Hoa")
s("STRINGS.RECIPE_DESC.XD_LUOSHEN_DINGHUNXIANGLU", "Áp chế cường độ thần hồn của bản thân")
s("STRINGS.RECIPE_DESC.XD_LUOSHEN_HUAXIA", "Có thể bảo đảm độ tươi của vật phẩm bên trong")
s("STRINGS.RECIPE_DESC.XD_LUOSHEN_HUAYIN", "Một cánh hoa nhân vẫn còn linh tính")
s("STRINGS.RECIPE_DESC.XD_LUOSHEN_HUAZHONG", "Trồng xuống cần dùng Chưởng Thiên Bình thúc đẩy hoa linh khai")
s("STRINGS.RECIPE_DESC.XD_LUOSHEN_JIANGREN", "Mềm mà sắc bén, phá giáp không tiếng")
s("STRINGS.RECIPE_DESC.XD_LUOSHEN_JIHUAZE", "Thi triển bẫy gai phạm vi rộng")
s("STRINGS.RECIPE_DESC.XD_LUOSHEN_LIFEFLOWER_BUILDER", "Chuyển hoá thành Sinh chi Hoa")
s("STRINGS.RECIPE_DESC.XD_LUOSHEN_LIUGUANGHUAFEN", "Sau khi dùng có thể tiến vào trạng thái linh hoá")
s("STRINGS.RECIPE_DESC.XD_LUOSHEN_PETALS", "Tiêu hao 10 điểm máu chế tạo một cánh hoa")
s("STRINGS.RECIPE_DESC.XD_LUOSHEN_PETALS_EVIL", "Tiêu hao 10 điểm máu chế tạo một cánh hoa sẫm màu")
s("STRINGS.RECIPE_DESC.XD_LUOSHEN_PLANTMEAT", "Huyết nhục của thực vật")
s("STRINGS.RECIPE_DESC.XD_LUOSHEN_YIN", "Một sợi ý hoa dẫn đường về")
s("STRINGS.RECIPE_DESC.XD_LYCX", "Linh tháp trói buộc Yêu Thú Long Nhặng")
s("STRINGS.RECIPE_DESC.XD_LYD", "Đèn đá điêu khắc có thể chiếu sáng phạm vi cực lớn")
s("STRINGS.RECIPE_DESC.XD_MG", "Hình như cả kẹo đường cũng có thể cất bên trong")
s("STRINGS.RECIPE_DESC.XD_MGLZ", "Từ xa đã ngửi được hương nấm")
s("STRINGS.RECIPE_DESC.XD_MO_BUILDER", "Ma Quân Hoá Thần kỳ có thể chưởng nắm")
s("STRINGS.RECIPE_DESC.XD_PFLNW", "Một căn nhà nhỏ có thể chăn nuôi bò lông dài")
s("STRINGS.RECIPE_DESC.XD_POG_HOUSE", "Nơi cư trú của Linh Hồ")
s("STRINGS.RECIPE_DESC.XD_QLJQ", "Đèn Quỳnh Lâu có thể chiếu sáng phạm vi khá lớn")
s("STRINGS.RECIPE_DESC.XD_QWSK", "Mỗi ngày có thể nhận một số món triều cống")
s("STRINGS.RECIPE_DESC.XD_SGC", "Có thể chứa lượng lớn lương thực")
s("STRINGS.RECIPE_DESC.XD_SJ_BGLXP", "Nội hữu càn khôn")
s("STRINGS.RECIPE_DESC.XD_SJ_BGYGP", "Ban cho Thân Ngoại Hoá Thân năng lực Hoàng Cân Lực Sĩ")
s("STRINGS.RECIPE_DESC.XD_SJ_BY", "Đồng tử siêng năng cần cù")
s("STRINGS.RECIPE_DESC.XD_SJ_BY_BUILDER", "Đồng tử siêng năng cần cù")
s("STRINGS.RECIPE_DESC.XD_SJ_CY", "Đồng tử cần cù u sầu")
s("STRINGS.RECIPE_DESC.XD_SJ_CY_BUILDER", "Đồng tử cần cù u sầu")
s("STRINGS.RECIPE_DESC.XD_SJ_KLS", "Bạch Cốt Động Khô Lâu Sơn")
s("STRINGS.RECIPE_DESC.XD_SJ_SXZ", "Giáp âm lạnh có vài kỳ hiệu")
s("STRINGS.RECIPE_DESC.XD_SJ_TLSQ", "Đá có linh khiếu, thần niệm có thể truyền tới")
s("STRINGS.RECIPE_DESC.XD_SJ_XSYDZ", "Điểm hoá ngoan thạch khiến chúng có linh trí hơn")
s("STRINGS.RECIPE_DESC.XD_SPIDERDEN", "Ma Châu bên trong hung ác vô cùng")
s("STRINGS.RECIPE_DESC.XD_STOOL", "Ngồi lên có vẻ tĩnh tâm ngưng thần")
s("STRINGS.RECIPE_DESC.XD_SUDAJI_REDLANTERN", "Đèn lồng xua tan giá lạnh và oi bức")
s("STRINGS.RECIPE_DESC.XD_SUDAJI_SJPN", "Túi nhỏ dệt từ tơ linh lực")
s("STRINGS.RECIPE_DESC.XD_SUDAJI_TSMD", "Có lẽ giờ kẻ giữ mộc điêu mới là thế thân")
s("STRINGS.RECIPE_DESC.XD_SUDAJI_YWFH", "Lấy đó để che một số tai ương khó tránh")
s("STRINGS.RECIPE_DESC.XD_TREE_DF", "Một cây phong chưa kịp đỏ thắm")
s("STRINGS.RECIPE_DESC.XD_TREE_LS", "Có sắc lá khá thanh đạm")
s("STRINGS.RECIPE_DESC.XD_TREE_XHS", "Không cần cành lá sum suê")
s("STRINGS.RECIPE_DESC.XD_TREE_YHS", "Cây anh đào được nuôi dưỡng từ linh thạch")
s("STRINGS.RECIPE_DESC.XD_TREE_YLS", "Có thể thấy cành liễu mềm trên đó")
s("STRINGS.RECIPE_DESC.XD_TREE_YXS", "Cành đầy lá vàng cam")
s("STRINGS.RECIPE_DESC.XD_WMZ_KJB", "Dưới cây tiên này, không nghịch không tôn nào tồn tại.")
s("STRINGS.RECIPE_DESC.XD_WMZ_MD1", "Mộc điêu Warg phụ thân sinh động")
s("STRINGS.RECIPE_DESC.XD_WMZ_MD2", "Mộc điêu Kim Phượng sinh động")
s("STRINGS.RECIPE_DESC.XD_WMZ_MD3", "Mộc điêu Cự Lộc sinh động")
s("STRINGS.RECIPE_DESC.XD_WMZ_MD4", "Mộc điêu Long Nhặng sinh động")
s("STRINGS.RECIPE_DESC.XD_WMZ_MD5", "Mộc điêu Mi Lộc Nga sinh động")
s("STRINGS.RECIPE_DESC.XD_WMZ_MD6", "Mộc điêu Kỳ Lân sinh động")
s("STRINGS.RECIPE_DESC.XD_WMZ_MD7", "Mộc điêu Hùng Hoan sinh động")
s("STRINGS.RECIPE_DESC.XD_WMZ_MD8", "Mộc điêu Viễn Cổ Chức Ảnh Giả sinh động")
s("STRINGS.RECIPE_DESC.XD_WMZ_SLXJ", "Triệu hồi Lục Mặc Phân Thân của bản thân")
s("STRINGS.RECIPE_DESC.XD_WSJX", "Có thể chứa một số thần binh lợi khí")
s("STRINGS.RECIPE_DESC.XD_WUKONG_DSMO", "Khi đủ điều kiện chuyển hình tướng Đại Thánh có thể dùng để chuyển")
s("STRINGS.RECIPE_DESC.XD_XCDF", "Có thể nâng phẩm chất đan dược")
s("STRINGS.RECIPE_DESC.XD_XIANJIAN_BUILDER", "Tiên Quân Hoá Thần kỳ có thể kích hoạt")
s("STRINGS.RECIPE_DESC.XD_XTBH", "Dùng để mang theo lưu trữ đan dược tiện lợi")
s("STRINGS.RECIPE_DESC.XD_XUANYU", "Cũng coi là vật trân quý hiếm có")
s("STRINGS.RECIPE_DESC.XD_YHSYZ", "Có thể trực tiếp thu hoạch linh thảo")
s("STRINGS.RECIPE_DESC.XD_YLXC", "Lưu trữ linh thảo mà không hư hỏng")
s("STRINGS.RECIPE_DESC.XD_YLXQ", "Vườn ươm tiên gia dùng trồng linh thảo")
s("STRINGS.RECIPE_DESC.XD_YUNXIAO_FGFQ", "Có thể gây địa chấn ở mức độ nhất định")
s("STRINGS.RECIPE_DESC.XD_YUNXIAO_FLS", "Có thể trói buộc mục tiêu trong thời gian ngắn")
s("STRINGS.RECIPE_DESC.XD_YUNXIAO_FYSZ", "Có thể độn tẩu cự ly xa")
s("STRINGS.RECIPE_DESC.XD_YUNXIAO_HYJDITEM", "Pháp khí hệ không gian")
s("STRINGS.RECIPE_DESC.XD_YUNXIAO_HYJDYQD", "Một trong chín điểm dịch chuyển của Hỗn Nguyên Kim Đấu")
s("STRINGS.RECIPE_DESC.XD_YUNXIAO_PORTABLE_SPICER", "Nêm gia vị hàng loạt cho món ăn")
s("STRINGS.RECIPE_DESC.XD_YUNXIAO_YMSZ", "Một bộ y phục khá thực dụng")
s("STRINGS.RECIPE_DESC.XD_ZHF", "Đã uẩn dưỡng nhiều hồn phách yêu thú")
s("STRINGS.RECIPE_DESC.XD_ZZXHCX", "Hang Hùng Hoan thường năm phủ tuyết do ảnh hưởng yêu thú")

-- =========================================================================
-- SJC / SOUL_WOLF / SUDAJI / SWHS / THANKS / UI / WONKEY / XD_*
-- =========================================================================
s("STRINGS.SJC_LEVELLIMIT", "Cần đợi một thời gian")
s("STRINGS.SOUL_WOLF_INCD", "Tàn hồn này trong thời gian ngắn không thể nghe lệnh ta nữa")
s("STRINGS.SOUL_WOLF_USELESS", "Ta không có đủ linh thạch")
s("STRINGS.SUDAJI_DEATG_TALKS.1", "Cô cần huyết nhục để ngưng luyện lại nhục thân ái phi")
s("STRINGS.SUDAJI_DEATG_TALKS.2", "Dám để ái phi của cô vong mạng, các ngươi ắt phải trả giá!")
s("STRINGS.SUDAJI_DEATG_TALKS.3", "Thân xác các ngươi sẽ trở thành một phần của ái phi!")
s("STRINGS.SUDAJI_DEATG_TALKS.4", "Hồn phách quy vị, các ngươi cứ chờ làm tế phẩm đi!")
s("STRINGS.SWHS_INCD", "Cần một chút thời gian để ngưng luyện lại thần thức")
s("STRINGS.SWHS_LEVELLIMIT", "Thần thức của ta vẫn chưa đủ mạnh")
s("STRINGS.THANKS_POPUP.DENGXIAN_SKINITEM", "Chúc đường tu tiên thênh thang!")
s("STRINGS.UI.CRAFTING_FILTERS.XD_TAB", "Tiên Đồ")
s("STRINGS.WONKEY_BIANSHEN", "Biến hoá")
s("STRINGS.XD_BADTARGETWORLD", "Thế giới mục tiêu lạc lối trong hư không")
s("STRINGS.XD_BY_INCD", "Tạm thời chưa thể tái tạo nhục thân mới của Bích Vân Đồng Tử.")
s("STRINGS.XD_CY_INCD", "Cần một ngày để ngưng tụ lại hồn phách")
s("STRINGS.XD_ENTER_HOUSE.ENTER", "Vào")
s("STRINGS.XD_ENTER_HOUSE.EXIT", "Rời khỏi")
s("STRINGS.XD_FUR_COOK", "Luyện chế")
s("STRINGS.XD_HTZ_NOLQ", "Linh lực không đủ")
s("STRINGS.XD_JINGWEI_FENICE_BUILDCD", "Cần thời gian ngưng tụ lại nhục thân Huyền Điểu, gom thần hồn")
s("STRINGS.XD_JINGWEI_FENICE_COOKTALK.1", "Tôn thượng, mời thử món sắc vị đều ngon này.")
s("STRINGS.XD_JINGWEI_FENICE_COOKTALK.2", "Tôn thượng, nếm thủ nghệ của tiểu nữ tử thế nào?")
s("STRINGS.XD_LEVEL_SKILLSTR.3", "Ta đã có thể thử triệu Thân Ngoại Hoá Thân")
s("STRINGS.XD_LEVEL_SKILLSTR.6", "Chính đạo ma đạo, đều ở một niệm của ta")
s("STRINGS.XD_LEVEL_SKILLSTR.9", "Linh lực của ta đủ để chưởng ngự Huyền Thiên Linh Bảo")
s("STRINGS.XD_LE_TBL.ALL", "Vô Câu Vô Thúc: nhận thêm 10% tốc độ di chuyển")
s("STRINGS.XD_LE_TBL.DEERCLOPS", "Đánh bại Cự Lộc: mùa hè nhận 120 điểm cách nhiệt")
s("STRINGS.XD_LE_TBL.KLAUS", "Đánh bại Klaus: nhận 25% giảm sát thương")
s("STRINGS.XD_LE_TBL.MUTATEDBEARGER", "Đánh bại Bearger Trang Giáp: Tai Khỉ có hiệu ứng bảo quản")
s("STRINGS.XD_LE_TBL.STALKER_ATRIUM", "Đánh bại Viễn Cổ Chức Ảnh Giả: mỗi phút hồi 6 điểm thần thức")
s("STRINGS.XD_LE_TBL.XD_JFSN", "Đánh bại Kim Phượng Thần Niệm: ngoài mùa hè nhận 120 điểm giữ ấm")
s("STRINGS.XD_LE_TBL.XD_QLCH", "Đánh bại Tàn Hồn Kỳ Lân: máu Thân Ngoại Hoá Thân tăng thêm 600")
s("STRINGS.XD_LONGZHU_SPELLSTR.1", "Giáng Vũ")
s("STRINGS.XD_LONGZHU_SPELLSTR.2", "Lạc Lôi")
s("STRINGS.XD_LONGZHU_SPELLSTR.3", "Băng Lao")
s("STRINGS.XD_LONGZHU_SPELLSTR.4", "Hàn Băng Pháp Trận")
s("STRINGS.XD_LONGZHU_SPELLSTR.5", "Không Gian Trữ Vật")
s("STRINGS.XD_LONGZHU_SPELLSTR.6", "Cực Quang")
s("STRINGS.XD_LONGZHU_SPELLSTR.7", "Băng Linh Hộ Thể")
s("STRINGS.XD_LONGZHU_SPELLSTR.8", "Hàn Băng Linh Nhãn")
s("STRINGS.XD_OTHERITEM", "Đây là vật phẩm cá nhân của người khác")
s("STRINGS.XD_QISHUACTIONSTR", "Kỳ Thuật")
s("STRINGS.XD_RESKIN_STR", "Đổi skin")
s("STRINGS.XD_SKILLS_TBL.AS_QS.LOCK", "Ta vẫn chưa học được kỳ thuật này…")
s("STRINGS.XD_SKILLS_TBL.AS_QS.OFF", "Kích hoạt khi đến Kết Đan kỳ")
s("STRINGS.XD_SKILLS_TBL.AS_QS.ON", "An Thân Thuật")
s("STRINGS.XD_SKILLS_TBL.AS_QS.UNLOCK", "Yêu quái chớ lại gần…")
s("STRINGS.XD_SKILLS_TBL.DS_QS.LOCK", "Một ngón định càn khôn…")
s("STRINGS.XD_SKILLS_TBL.DS_QS.OFF", "Định Thân Thuật")
s("STRINGS.XD_SKILLS_TBL.DS_QS.ON", "Định Thân Thuật")
s("STRINGS.XD_SKILLS_TBL.DS_QS.UNLOCK", "Một ngón định càn khôn…")
s("STRINGS.XD_SKILLS_TBL.JXSQ_LJ.LOCK", "Ta vẫn chưa học được linh kỹ này…")
s("STRINGS.XD_SKILLS_TBL.JXSQ_LJ.OFF", "Tụ Hình Tán Khí")
s("STRINGS.XD_SKILLS_TBL.JXSQ_LJ.ON", "Tụ Hình Tán Khí")
s("STRINGS.XD_SKILLS_TBL.JXSQ_LJ.UNLOCK", "Hữu hình diệc vô hình…")
s("STRINGS.XD_SKILLS_TBL.TTTB_LJ.LOCK", "Ta vẫn chưa học được linh kỹ này…")
s("STRINGS.XD_SKILLS_TBL.TTTB_LJ.OFF", "Kích hoạt khi đến Trúc Cơ kỳ")
s("STRINGS.XD_SKILLS_TBL.TTTB_LJ.ON", "Đồng Đầu Thiết Tý")
s("STRINGS.XD_SKILLS_TBL.TTTB_LJ.UNLOCK", "Tay tựa kim loại, đầu cứng hơn đồng…")
s("STRINGS.XD_STG_CANTEAT", "Hai ngày này ăn lại có lẽ không tác dụng gì")
s("STRINGS.XD_TAB", "Tiên Đồ")
s("STRINGS.XD_TUPO_BUSY", "Ta tạm thời không thể tiếp nhận lượng linh lực lớn như vậy!")
s("STRINGS.XD_TUPO_USELESS", "Nó với việc tu luyện của ta đã không còn tác dụng")
s("STRINGS.XD_USE_GCSZ_FALSE", "Cho dù kích hoạt cũng không vận hành được Truyền Tống Trận này")
s("STRINGS.XD_USE_LLBX_FALSE", "Phúc trạch này có thể khiến ta hoài bích kỳ tội")
s("STRINGS.XD_WENYANG", "Ôn dưỡng")
s("STRINGS.XD_WUKONG_TALKS.BSLOCKED", "Lão Tôn ta vẫn chưa học được biến hoá chi thuật này...")
s("STRINGS.XD_WUKONG_TALKS.CHOSEBS", "Vừa thật vừa giả, chân nguỵ khó phân…")
s("STRINGS.XD_ZTP_USELESS", "Cần ngưng tụ thêm nhiều linh khí thiên địa")
s("STRINGS.XS_HUAPENACTIONS_STR", "Thêm")
s("STRINGS.XS_NOTMYSWHS", "Thân Ngoại Hoá Thân này ngưng tụ thần thức của người khác")
s("STRINGS.XS_SWHS_UNEQUIP", "Tháo giáp")
s("STRINGS.XS_WEAPON_REPAIR.REPAIR", "Thôn phệ")
s("STRINGS.XS_WEAPON_REPAIR.RONGHE", "Dung hợp")

-- =========================================================================
-- SKIN_DESCRIPTIONS / SKIN_NAMES / SKIN_QUOTES (~210)
-- =========================================================================
s("STRINGS.SKIN_DESCRIPTIONS.xd_hantianzun_qh", "Thân Ngoại Hoá Thân ngưng kết Sát Đan.")
s("STRINGS.SKIN_DESCRIPTIONS.xd_hantianzun_qzxx", "Ta vốn là sơn dã nhàn nhân, các hạ hà tất quấy nhiễu thanh tịnh ta?")
s("STRINGS.SKIN_DESCRIPTIONS.xd_hantianzun_zymj", "Ngoại hình Tử Vân Ma Quân do Huyễn Hình Quyết hoá thành.")
s("STRINGS.SKIN_DESCRIPTIONS.xd_jingwei_clys", "Lời chúc năm mới đã đến~")
s("STRINGS.SKIN_DESCRIPTIONS.xd_jingwei_dfjm", "Lá phong say đỏ trong sắc thu, hai ba hàng nhạn giữa tà dương.")
s("STRINGS.SKIN_DESCRIPTIONS.xd_jingwei_gxsl", "Thiên hương sinh thanh tưởng, vân ảnh hộ tiên trang.")
s("STRINGS.SKIN_DESCRIPTIONS.xd_longtaizi_hysj", "Ngàn búa vạn đục ra khỏi sơn, lửa lớn đốt cháy như tự nhiên.")
s("STRINGS.SKIN_DESCRIPTIONS.xd_longtaizi_nl", "Kim lân vỡ vụn cốt rắn rỏi, tự gỡ nghịch lân đúc lưỡi sắc.")
s("STRINGS.SKIN_DESCRIPTIONS.xd_luoshen_mksny", "Phong ấn đã giải!")
s("STRINGS.SKIN_DESCRIPTIONS.xd_shiji_jyxx", "Lấy hà quang mê loạn tinh đẩu.")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_cgsh", "Xích Cốt Sinh Hoa")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_clzgj", "Thúy Linh Chỉ Qua Kiếm")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_cxlt", "Xích Tiêu Long Đằng")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_cygh", "Thúy Vũ Quang Hoa")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_fgy", "Phượng Quy Vân")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_fhjd", "Phong Hoa Tuyệt Đại")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_flzr", "Phượng Linh Trọng Nhận")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_fsfmg", "Phược Thần Phong Ma Côn")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_fshm", "Phù Sinh Hội Mộng")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_fyzz", "Phong Ấn Chi Trượng")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_hasaki", "Hasaki")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_hyys", "Hà Nhan Nguyệt Sắc")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_jj", "Giao Cơ")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_jydm", "Kinh Vũ Điểm Mặc")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_jypk", "Cẩm Vũ Phá Không")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_kt", "Khai Thiên")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_ly", "Linh Dực")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_lysy", "Lưu Vân Sóc Ảnh")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_mzhcd", "Minh Châu Hoa Thải Đao")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_mzly", "Mặc Trúc Long Ngâm")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_nczx", "Nghịch Trần Tử Huyết")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_ny", "Nghịch Nha")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_nyhr", "Nghịch Vũ Huyễn Nhận")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_smy", "Tễ Ma Dẫn")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_tf", "Thính Phong")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_wxj", "Vấn Tâm Kiếm")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_wzsb", "Tẫn Hải Thương Mang")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_xgl", "Tiên Cốt Lệ")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_xqc", "Tuyết Khuynh Thành")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_xuanyuan", "Hiên Viên")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_xyb", "Tinh Nguyệt Bổng")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_yfcy", "Nhai Phong Trào Vũ")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_yfly", "Hữu Phượng Lai Nghi")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_ylxh", "Say rồi không biết trời trong nước, đầy thuyền mộng thanh đè tinh hà")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_ysb", "Diễn Thần Binh")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_zste", "Tử Sát Thái A")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_zsxm", "Trang Sinh Hiểu Mộng")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_zw", "Trấn Ác")
s("STRINGS.SKIN_DESCRIPTIONS.xd_skin_zyj", "Tử Doanh Kiếp")
s("STRINGS.SKIN_DESCRIPTIONS.xd_sudaji_gstx", "Bạch Phượng chiếu thư đến đã muộn, lục cung phấn lệ nửa xuân tàn.")
s("STRINGS.SKIN_DESCRIPTIONS.xd_sudaji_qrsy", "Lá phong ngàn cành rồi vạn cành, cầu sông che khuất buồm đêm chậm.")
s("STRINGS.SKIN_DESCRIPTIONS.xd_sudaji_qsdc", "Phong Tình sơn rỉ thúy thuỷ pha lam, tụ tán ngư chu hai ba lượt.")
s("STRINGS.SKIN_DESCRIPTIONS.xd_sudaji_wcgz", "Bạc mệnh nghiêng Trường An, nhan sắc về Tây Thổ. Lục lục công chúa liễu, rủ phất say nga mi.")
s("STRINGS.SKIN_DESCRIPTIONS.xd_wangmazi_jxgs", "Ma tiền một khấu ba ngàn năm, ngoái lại phàm trần không làm tiên.")
s("STRINGS.SKIN_DESCRIPTIONS.xd_wangmazi_tymh", "Tận đầu pháp tắc, không một vật.")
s("STRINGS.SKIN_DESCRIPTIONS.xd_wukong_ds", "Mình mặc kim giáp sáng rực rỡ, đầu đội kim quan ánh long lanh.")
s("STRINGS.SKIN_DESCRIPTIONS.xd_wukong_hsmy", "Không gì có thể trói buộc con khỉ này.")
s("STRINGS.SKIN_DESCRIPTIONS.xd_wukong_sxz", "Hàng yêu trừ quái Tôn Hành Giả, hộ pháp Tây Thiên thỉnh thánh kinh.")
s("STRINGS.SKIN_DESCRIPTIONS.xd_yunxiao_msnzs", "Trăng dưới chuông vang, thời khắc biến thân!")
s("STRINGS.SKIN_DESCRIPTIONS.xd_yunxiao_zwzy", "Tình hà rực rỡ phủ rìa mái, giáng tuyết lất phất điểm bậc cát")

-- SKIN_NAMES (apply substring fallback for repeats: many same as SKIN_DESC)
s("STRINGS.SKIN_NAMES.xd_backpack3_skin1", "Quy Uyên")
s("STRINGS.SKIN_NAMES.xd_backpack3_skin2", "Ba lô U Hoàng")
s("STRINGS.SKIN_NAMES.xd_backpack3_skin3", "Ba lô Thiên La")
s("STRINGS.SKIN_NAMES.xd_backpack3_skin4", "Áo ngoài Bát Vĩ Vĩ Thú")
s("STRINGS.SKIN_NAMES.xd_backpack3_skin5", "Thí Ngô Vũ Dực")
s("STRINGS.SKIN_NAMES.xd_crc_skins_hqyx", "Hoa Tiền Nguyệt Hạ")
s("STRINGS.SKIN_NAMES.xd_dbg_skins_llt", "Lâm Lang Đài")
s("STRINGS.SKIN_NAMES.xd_dbg_skins_ybg", "Dị Bảo Các")
s("STRINGS.SKIN_NAMES.xd_dc_skins_hh", "Hằng Huy")
s("STRINGS.SKIN_NAMES.xd_flower_bmg_skins_srlg", "Tơ Nhung Lưu Quang")
s("STRINGS.SKIN_NAMES.xd_flower_md_skins_rjfg", "Nhân Gian Phú Quý")
s("STRINGS.SKIN_NAMES.xd_flower_sfr_skins_fr", "Phù Dung")
s("STRINGS.SKIN_NAMES.xd_flower_sfr_skins_xy", "Tịch Nhan")
s("STRINGS.SKIN_NAMES.xd_ftys_skins_zjzy", "Chước Kim Soạn Ngọc")
s("STRINGS.SKIN_NAMES.xd_gj_skins_lrq", "Lạc Tinh Tuyền")
s("STRINGS.SKIN_NAMES.xd_gjx_skins_jsth", "Cẩm Thượng Thiêm Hoa")
s("STRINGS.SKIN_NAMES.xd_hantianzun_none", "Hàn Thiên Tôn")
s("STRINGS.SKIN_NAMES.xd_hantianzun_qh", "Khúc Hồn")
s("STRINGS.SKIN_NAMES.xd_hantianzun_qzxx", "Thanh Trúc Tiểu Hiên")
s("STRINGS.SKIN_NAMES.xd_hantianzun_zymj", "Tử Vân Ma Quân")
s("STRINGS.SKIN_NAMES.xd_hhlmz_skins_htjc", "Hoa Đoàn Cẩm Thốc")
s("STRINGS.SKIN_NAMES.xd_hhlmz_skins_wfz", "Vạn Phúc Trác")
s("STRINGS.SKIN_NAMES.xd_hmsw_skins_bzxw", "Bắc Minh Tiểu Trúc")
s("STRINGS.SKIN_NAMES.xd_jingwei_clys", "Xích Linh Nghênh Tuế")
s("STRINGS.SKIN_NAMES.xd_jingwei_dfjm", "Đan Phong Kim Mộng")
s("STRINGS.SKIN_NAMES.xd_jingwei_gxsl", "Quế Hương Thập Lý")
s("STRINGS.SKIN_NAMES.xd_jingwei_none", "Tinh Vệ")
s("STRINGS.SKIN_NAMES.xd_jwtcd_skins_hqy", "Hoa Thê Ảnh")
s("STRINGS.SKIN_NAMES.xd_jwtcd_skins_qzyc", "Quỳnh Châu Dật Thải")
s("STRINGS.SKIN_NAMES.xd_lbjlt_skins_zgrpt", "Truy Quang Dung Phách Đài")
s("STRINGS.SKIN_NAMES.xd_lgzbh_skins_jlyc", "Kim Lân Ánh Tài")
s("STRINGS.SKIN_NAMES.xd_liandanlu_skins_ysx", "Dị Thế Hương")
s("STRINGS.SKIN_NAMES.xd_longtaizi_hysj", "Hỏa Vân Thần Quân")
s("STRINGS.SKIN_NAMES.xd_longtaizi_nl", "Nghịch Lân Thái Tử")
s("STRINGS.SKIN_NAMES.xd_longtaizi_none", "Long Thái Tử")
s("STRINGS.SKIN_NAMES.xd_luoshen_mksny", "Mocha Thiếu Nữ Cherry")
s("STRINGS.SKIN_NAMES.xd_luoshen_none", "Lạc Thần")
s("STRINGS.SKIN_NAMES.xd_lyd_skins_fhgz", "Phù Hoa Quy Chân")
s("STRINGS.SKIN_NAMES.xd_mg_skins_qwg", "Thanh Ngoã Quán")
s("STRINGS.SKIN_NAMES.xd_mglz_skins_hhyy", "Hoa Hảo Nguyệt Viên")
s("STRINGS.SKIN_NAMES.xd_mo_builder_skins_duanzui", "<Đoán Tội> Ma Kiếm")
s("STRINGS.SKIN_NAMES.xd_mo_builder_skins_wendao", "<Vấn Đạo> Ma Kiếm")
s("STRINGS.SKIN_NAMES.xd_pflnw_skins_qns", "Thanh Ngưu Xá")
s("STRINGS.SKIN_NAMES.xd_qljq_skins_hlq", "Hải Long Kình")
s("STRINGS.SKIN_NAMES.xd_qwsk_xznw", "Hàm Chi Nạp Vị")
s("STRINGS.SKIN_NAMES.xd_sgc_skins_wgc", "Ngũ Cốc Thương")
s("STRINGS.SKIN_NAMES.xd_shiji_jyxx", "Cửu U Huyền Hà")
s("STRINGS.SKIN_NAMES.xd_shiji_none", "Thạch Cơ Nương Nương")
s("STRINGS.SKIN_NAMES.xd_sj_by_skin1", "Bích Hải Vân Đồng")
s("STRINGS.SKIN_NAMES.xd_sj_cy_skin1", "Đường Hạ Vân Đồng")
s("STRINGS.SKIN_NAMES.xd_skin_cgsh", "Xích Cốt Sinh Hoa")
s("STRINGS.SKIN_NAMES.xd_skin_clzgj", "Thúy Linh Chỉ Qua Kiếm")
s("STRINGS.SKIN_NAMES.xd_skin_cxlt", "Xích Tiêu Long Đằng")
s("STRINGS.SKIN_NAMES.xd_skin_cygh", "Thúy Vũ Quang Hoa")
s("STRINGS.SKIN_NAMES.xd_skin_fgy", "Phượng Quy Vân")
s("STRINGS.SKIN_NAMES.xd_skin_fhjd", "Phong Hoa Tuyệt Đại")
s("STRINGS.SKIN_NAMES.xd_skin_flzr", "Phượng Linh Trọng Nhận")
s("STRINGS.SKIN_NAMES.xd_skin_fsfmg", "Phược Thần Phong Ma Côn")
s("STRINGS.SKIN_NAMES.xd_skin_fshm", "Phù Sinh Hội Mộng")
s("STRINGS.SKIN_NAMES.xd_skin_fyzz", "Phong Ấn Chi Trượng")
s("STRINGS.SKIN_NAMES.xd_skin_hasaki", "Hasaki")
s("STRINGS.SKIN_NAMES.xd_skin_hyys", "Hà Nhan Nguyệt Sắc")
s("STRINGS.SKIN_NAMES.xd_skin_jj", "Giao Cơ")
s("STRINGS.SKIN_NAMES.xd_skin_jydm", "Kinh Vũ Điểm Mặc")
s("STRINGS.SKIN_NAMES.xd_skin_jypk", "Cẩm Vũ Phá Không")
s("STRINGS.SKIN_NAMES.xd_skin_kt", "Khai Thiên")
s("STRINGS.SKIN_NAMES.xd_skin_ly", "Linh Dực")
s("STRINGS.SKIN_NAMES.xd_skin_lysy", "Lưu Vân Sóc Ảnh")
s("STRINGS.SKIN_NAMES.xd_skin_mzhcd", "Minh Châu Hoa Thải Đao")
s("STRINGS.SKIN_NAMES.xd_skin_mzly", "Mặc Trúc Long Ngâm")
s("STRINGS.SKIN_NAMES.xd_skin_nczx", "Nghịch Trần Tử Huyết")
s("STRINGS.SKIN_NAMES.xd_skin_ny", "Nghịch Nha")
s("STRINGS.SKIN_NAMES.xd_skin_nyhr", "Nghịch Vũ Huyễn Nhận")
s("STRINGS.SKIN_NAMES.xd_skin_smy", "Tễ Ma Dẫn")
s("STRINGS.SKIN_NAMES.xd_skin_tf", "Thính Phong")
s("STRINGS.SKIN_NAMES.xd_skin_wxj", "Vấn Tâm Kiếm")
s("STRINGS.SKIN_NAMES.xd_skin_wzsb", "Tẫn Hải Thương Mang")
s("STRINGS.SKIN_NAMES.xd_skin_xgl", "Tiên Cốt Lệ")
s("STRINGS.SKIN_NAMES.xd_skin_xqc", "Tuyết Khuynh Thành")
s("STRINGS.SKIN_NAMES.xd_skin_xuanyuan", "Hiên Viên")
s("STRINGS.SKIN_NAMES.xd_skin_xyb", "Tinh Nguyệt Bổng")
s("STRINGS.SKIN_NAMES.xd_skin_yfcy", "Nhai Phong Trào Vũ")
s("STRINGS.SKIN_NAMES.xd_skin_yfly", "Hữu Phượng Lai Nghi")
s("STRINGS.SKIN_NAMES.xd_skin_ylxh", "Nhất Lãm Tinh Hà")
s("STRINGS.SKIN_NAMES.xd_skin_ysb", "Diễn Thần Binh")
s("STRINGS.SKIN_NAMES.xd_skin_zste", "Tử Sát Thái A")
s("STRINGS.SKIN_NAMES.xd_skin_zsxm", "Trang Sinh Hiểu Mộng")
s("STRINGS.SKIN_NAMES.xd_skin_zw", "Trấn Ác")
s("STRINGS.SKIN_NAMES.xd_skin_zyj", "Tử Doanh Kiếp")
s("STRINGS.SKIN_NAMES.xd_soul_wolf_zmyh", "Chu Minh Dược Hồng")
s("STRINGS.SKIN_NAMES.xd_sudaji_gstx", "Quốc Sắc Thiên Hương")
s("STRINGS.SKIN_NAMES.xd_sudaji_none", "Tô Đát Kỷ")
s("STRINGS.SKIN_NAMES.xd_sudaji_qrsy", "Thu Nhật Tư Ngữ")
s("STRINGS.SKIN_NAMES.xd_sudaji_qsdc", "Tình Sơn Rỉ Thúy")
s("STRINGS.SKIN_NAMES.xd_sudaji_redlantern_zyx", "Chiếu Dạ Hành")
s("STRINGS.SKIN_NAMES.xd_sudaji_sjpn_jssc", "Cẩm Thượng Thập Thải")
s("STRINGS.SKIN_NAMES.xd_sudaji_tsmd_ykmd", "Duyên Khắc Mộc Điêu")
s("STRINGS.SKIN_NAMES.xd_sudaji_wcgz", "Văn Thành Công Chúa")
s("STRINGS.SKIN_NAMES.xd_sudaji_yhly_yhm", "Ngọc Hồ Miên")
s("STRINGS.SKIN_NAMES.xd_sudaji_ywfh_lxzy", "La Tụ Già Diêm")
s("STRINGS.SKIN_NAMES.xd_tianjiwu_skins_byj", "Bạch Ngọc Kinh")
s("STRINGS.SKIN_NAMES.xd_tree_df_skins_zsyj", "Chu Thị Ánh Kim")
s("STRINGS.SKIN_NAMES.xd_tree_xhs_skins_lgs", "Lang Can Thụ")
s("STRINGS.SKIN_NAMES.xd_tree_yhs_skins_fd", "Phấn Đại")
s("STRINGS.SKIN_NAMES.xd_tree_yxs_skins_jqs", "Cây Kim Tiền")
s("STRINGS.SKIN_NAMES.xd_wangmazi_jxgs", "Cổ Thần Chi Thể")
s("STRINGS.SKIN_NAMES.xd_wangmazi_none", "Vương Ma Tử")
s("STRINGS.SKIN_NAMES.xd_wangmazi_tymh", "Thiên Hành Ma Hài")
s("STRINGS.SKIN_NAMES.xd_wsjx_skins_yzjx", "Ngọc Trạch Kiếm Hợp")
s("STRINGS.SKIN_NAMES.xd_wukong_ds", "Đại Thánh")
s("STRINGS.SKIN_NAMES.xd_wukong_hsmy", "Hỗn Thế Ma Viên")
s("STRINGS.SKIN_NAMES.xd_wukong_none", "Tôn Ngộ Không")
s("STRINGS.SKIN_NAMES.xd_wukong_sxz", "Tôn Hành Giả")
s("STRINGS.SKIN_NAMES.xd_xcdf_skins_sysx", "Song Ngư Tố Tinh")
s("STRINGS.SKIN_NAMES.xd_xianjian_builder_skins_duanzui", "<Đoán Tội> Tiên Kiếm")
s("STRINGS.SKIN_NAMES.xd_xianjian_builder_skins_wendao", "<Vấn Đạo> Tiên Kiếm")
s("STRINGS.SKIN_NAMES.xd_xshj_bbzy", "Bích Ba Trúc Ảnh")
s("STRINGS.SKIN_NAMES.xd_xshj_fhlh", "Phong Hoa Lưu Hỏa")
s("STRINGS.SKIN_NAMES.xd_xtbh_skins_wxxxh", "Vạn Tượng Tinh Toàn Hồ")
s("STRINGS.SKIN_NAMES.xd_yaoarmor", "Thanh La Thường")
s("STRINGS.SKIN_NAMES.xd_yaohat", "Lộc Linh Dung")
s("STRINGS.SKIN_NAMES.xd_yhbs_zmyh", "Chu Minh Dược Hồng")
s("STRINGS.SKIN_NAMES.xd_yhsyz_skins_qlyyz", "Thanh Lộ Dẫn Dược Chi")
s("STRINGS.SKIN_NAMES.xd_ylxc_skins_qhnlc", "Thanh Hà Ngưng Lộ Thương")
s("STRINGS.SKIN_NAMES.xd_ylxq_skins_fynl", "Phỉ Yên Ngưng Lộ")
s("STRINGS.SKIN_NAMES.xd_yunxiao_msnzs", "Mỹ Thiếu Nữ Chiến Sĩ")
s("STRINGS.SKIN_NAMES.xd_yunxiao_none", "Tam Tiêu Nương Nương")
s("STRINGS.SKIN_NAMES.xd_yunxiao_zwzy", "Tử Vi Triều Dương")
s("STRINGS.SKIN_NAMES.xd_zcmj_jhxs", "Kim Huy Tường Thủ")
s("STRINGS.SKIN_NAMES.xd_zcmj_trxz", "Đoàn Nhung Hí Châu")
s("STRINGS.SKIN_NAMES.xd_ztp_skins_lmxq", "Linh Mộc Tiên Cừ")

s("STRINGS.SKIN_QUOTES.xd_hantianzun_qh", "Mệnh, không thể đổi.")
s("STRINGS.SKIN_QUOTES.xd_hantianzun_qzxx", "Hiên ngoại ngàn cây trúc, tâm gian một niệm nhàn.")
s("STRINGS.SKIN_QUOTES.xd_hantianzun_zymj", "Chân giả khó phân, niệm huyễn hình.")
s("STRINGS.SKIN_QUOTES.xd_jingwei_clys", "Phúc như Đông Hải, bay đến đây—!")
s("STRINGS.SKIN_QUOTES.xd_jingwei_dfjm", "Có thích bộ y phục này của ta không?")
s("STRINGS.SKIN_QUOTES.xd_jingwei_gxsl", "Ta thật sự thích bộ kim trang này.")
s("STRINGS.SKIN_QUOTES.xd_longtaizi_hysj", "Bản Thái Tử khả không phải kẻ tầm thường.")
s("STRINGS.SKIN_QUOTES.xd_longtaizi_nl", "Cúi đầu trước ai? Trời đất cũng không bắt được ta cúi đầu.")
s("STRINGS.SKIN_QUOTES.xd_luoshen_mksny", "Tuyệt đối không thành vấn đề!")
s("STRINGS.SKIN_QUOTES.xd_shiji_jyxx", "Bản tọa cũng không muốn làm tới cùng.")
s("STRINGS.SKIN_QUOTES.xd_sudaji_gstx", "Để thiếp thân biểu diễn cho đại vương một khúc.")
s("STRINGS.SKIN_QUOTES.xd_sudaji_qrsy", "Thiếp thân có khiến chàng cảm thấy chút lạnh lẽo không?")
s("STRINGS.SKIN_QUOTES.xd_sudaji_qsdc", "Thiếp thân thế này có vẻ hơi khắc bạc?")
s("STRINGS.SKIN_QUOTES.xd_sudaji_wcgz", "Thiếp thân không muốn lại bước vào cuộc này.")
s("STRINGS.SKIN_QUOTES.xd_wangmazi_jxgs", "Người không phạm ta, ta không phạm người!")
s("STRINGS.SKIN_QUOTES.xd_wangmazi_tymh", "Đạo của ta, là lỗ hổng duy nhất của thiên đạo.")
s("STRINGS.SKIN_QUOTES.xd_wukong_ds", "Lão Tôn ta xưa nay chưa từng sợ ai.")
s("STRINGS.SKIN_QUOTES.xd_wukong_hsmy", "Ta muốn trời này không che được mắt ta!")
s("STRINGS.SKIN_QUOTES.xd_wukong_sxz", "Đây! Yêu quái!")
s("STRINGS.SKIN_QUOTES.xd_yunxiao_msnzs", "Thay mặt nguyệt thần, trừng phạt ngươi!")
s("STRINGS.SKIN_QUOTES.xd_yunxiao_zwzy", "Không vui vì vật, không buồn vì mình.")

print("[DangTienVN] Phase 2 strings applied.")
